### ISSUE TITLE
Zahnräder bei Update

### ISSUE THREAD

**Issue by LJSven** [iobroker-community-adapters/ioBroker.enigma2#10]
Hallo, ich habe heute nochmal deinen Adapter installiert - 2 Instanzen. Ich habe nach wie vor das Problem, daß der Adapter Zahnräder erzeugt (auf 2 Boxen), wenn er sich die Infos holt. Alles ist via LAN angeschlossen. Was mache ich falsch, wie kann ich es ändern?

**Comment by Matten-Matten** [comment]
Nimm Mal das Poll Intervall hoch auf 8 oder 10 sec. Vermutlich kommt deine Box nicht mit den vielen Anfragen klar.

Gruß 
Matten Matten

**Comment by LJSven** [comment]
Beide Boxen stehen auf 15 Sekunden.

**Comment by Matten-Matten** [comment]
OK, was sind das für Boxen?

**Comment by Matten-Matten** [comment]
Und welches Webinterface nutzt du?

**Comment by LJSven** [comment]
Dreambox 7020HD & DB 500 HD beide mit der aktuellsten NN2 Firmware. Webinterface ist das was mit der NN2 mitgeliefiert wird.

**Comment by Matten-Matten** [comment]
OK bei der dm500 kann ich mir das vorstellen. Du kannst höchstens Mal das Open webif testen.

Wenn das nix ändert kann ich ja Mal schauen, ob man dann in der Konfigurations Maske ein paar abfragen deaktivieren kann für solche schwachen Boxen.

**Comment by LJSven** [comment]
Bei meiner DB 7020HD habe ich das gleiche Problem. Bekomme das open web leider nicht installiert. Es fehlen zwei Phyton Pakete. Was kann ich da machen?

**Comment by Pocky2507** [comment]
Dann zeig doch mal den Consolenlog vom installieren des WebIf.
Obwohl ich mir fast sicher bin das NN das OpenWebIf benutzt.

**Comment by LJSven** [comment]
NN hat wohl nicht das OpenWebif - hier der Fehler beim installieren:

`root@dm500hdv2:/var/volatile/tmp# opkg install ./enigma2-plugin-extensions-openwebif_2.0_mips32el.ipk
Multiple packages (enigma2-plugin-extensions-openwebif and enigma2-plugin-extensions-openwebif) providing same name marked HOLD or PREFER. Using latest.
Installing enigma2-plugin-extensions-openwebif (2.0) to flash...
Collected errors:
 * check_data_file_clashes: Package enigma2-plugin-extensions-openwebif wants to install file /usr/lib/python2.7/lib-dynload/_json.so
	But that file is already provided by package  * python-json
 * check_data_file_clashes: Package enigma2-plugin-extensions-openwebif wants to install file /usr/lib/python2.7/json/encoder.py
	But that file is already provided by package  * python-json
 * check_data_file_clashes: Package enigma2-plugin-extensions-openwebif wants to install file /usr/lib/python2.7/json/scanner.py
	But that file is already provided by package  * python-json
 * check_data_file_clashes: Package enigma2-plugin-extensions-openwebif wants to install file /usr/lib/python2.7/json/__init__.py
	But that file is already provided by package  * python-json
 * check_data_file_clashes: Package enigma2-plugin-extensions-openwebif wants to install file /usr/lib/python2.7/json/decoder.py
	But that file is already provided by package  * python-json
 * check_data_file_clashes: Package enigma2-plugin-extensions-openwebif wants to install file /usr/lib/python2.7/json/tool.py
	But that file is already provided by package  * python-json
 * check_data_file_clashes: Package enigma2-plugin-extensions-openwebif wants to install file /usr/lib/python2.7/pprint.py
	But that file is already provided by package  * python-pprint
 * opkg_install_cmd: Cannot install package enigma2-plugin-extensions-openwebif.`

**Comment by Pocky2507** [comment]
Nach diesem Log:
`Multiple packages (enigma2-plugin-extensions-openwebif and enigma2-plugin-extensions-openwebif) `
ist das OpenWebIf aber bereits installiert.
Fehlen tuen Dir auch keine Pakete, die sind bereits installiert.
Du kannst das ja mal deinstallieren, neustart und nochmal installieren.
ipkg remove enigma2-plugin-extensions-openwebif *
oder
opkg remove enigma2-plugin-extensions-openwebif*
Weiß die Befehle für diese doch sehr alten OE Versionen nicht mehr genau.

Zur Not mal nen OpenATV Image drauf machen.
Die arbeiten definitiv mit dem OpenWebIf

Mach mal nen Screenshot vom WebIf

Für die 7080 kannst Du mal diese Version testen.
Läuft bei mir auf ner dm525
[OpnenWebIf.zip](https://github.com/Matten-Matten/ioBroker.enigma2/files/2635670/OpnenWebIf.zip)

**Comment by LJSven** [comment]
Ich habe eine 7020HD / keine 7080. Würde gern bei dem Image bleiben, wenn möglich.
![0a8f38d1-94c7-43eb-a53c-ba9c664a8456](https://user-images.githubusercontent.com/8560588/49325928-a33eff80-f54a-11e8-9cdc-caa6db542681.png)
![b3e05e80-830a-49ac-a3b2-f2a2bf6d3a8b](https://user-images.githubusercontent.com/8560588/49325929-a3d79600-f54a-11e8-800c-a2bdf113b3cb.png)

**Comment by Pocky2507** [comment]
Hmm, Hast Du den Zugriff erlaubt?
Schau Dir in den WebIf Einstellungen ob Du diese Einstellungen hast:
Findest Du unter Einstellungen - Erweiterungen - WebIf
Die unteren beiden.
Das kann man schlecht lesen, sollte auf deaktivieren stehen.
![webif](https://user-images.githubusercontent.com/22934504/49328949-e0ba8180-f578-11e8-86ef-e916f126c488.png)

**Comment by Matten-Matten** [comment]
Wurde das Problem gelöst?

**Comment by LJSven** [comment]
Ja, mit dem OpenATV Image läuft es - obwohl ich mit der Lösung nicht happy bin, da ich da andere Probleme habe.

**Comment by Matten-Matten** [comment]
ok dann ist es jedoch kein Problem vom Adapter, sondern vom Box Image.

**Comment by Matten-Matten** [comment]
Grundsätzlich finde ich OpenATV sehr gut. was funktioniert denn nicht?

**Comment by LJSven** [comment]
Bei mir wird das Menü aufgerufen, obwohl ich nichts mache - Rolläden sind runter, Fernbedienung nicht in der Hand und Alle Ports gesperrt.

**Comment by Matten-Matten** [comment]
könnte ein hdmi cec problem sein, das image ist aktuell?

**Comment by LJSven** [comment]
6.1 - aktueller geht es nicht auf der DM 7020 HD

**Comment by Matten-Matten** [comment]
http://images.mynonpublic.com/openatv/current/index.php?open=dm7020hd

da gibt es 6.2

**Comment by LJSven** [comment]
Die habe ich versucht zu installieren - beim Flashen hat er immer bei 98% abgebrochen. 6.1 lief problemlos durch

**Comment by Matten-Matten** [comment]
oh ok. von der DM 7020 HD gibt es auch noch eine V2 version, hoffe du hast darauf geachtet?
