### ISSUE TITLE
After update to js-controller 5.0.6 errors 

### ISSUE THREAD

**Issue by Michaelnorge** [iobroker-community-adapters/ioBroker.enigma2#100]
After update to jsc 5.0.6. the adapter try rebuild but is not starting.

`<html>
<body>

host.raspberrypi | 2023-07-09 21:05:46.372 | info | Rebuild for adapter system.adapter.enigma2.0 not successful in 3 tries. Adapter will not be restarted again. Please execute "npm install --production" in adapter directory manually.
-- | -- | -- | --
host.raspberrypi | 2023-07-09 21:05:46.372 | error | instance system.adapter.enigma2.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
host.raspberrypi | 2023-07-09 21:05:46.372 | error | Caught by controller[0]: Node.js v18.16.0
host.raspberrypi | 2023-07-09 21:05:46.371 | error | Caught by controller[0]: }
host.raspberrypi | 2023-07-09 21:05:46.371 | error | Caught by controller[0]: ]
host.raspberrypi | 2023-07-09 21:05:46.371 | error | Caught by controller[0]: '/opt/iobroker/node_modules/iobroker.enigma2/main.js'
host.raspberrypi | 2023-07-09 21:05:46.371 | error | Caught by controller[0]: '/opt/iobroker/node_modules/iobroker.enigma2/lib/utils.js',
host.raspberrypi | 2023-07-09 21:05:46.371 | error | Caught by controller[0]: requireStack: [
host.raspberrypi | 2023-07-09 21:05:46.371 | error | Caught by controller[0]: code: 'MODULE_NOT_FOUND',
host.raspberrypi | 2023-07-09 21:05:46.371 | error | Caught by controller[0]: at Module.require (node:internal/modules/cjs/loader:1141:19) {
host.raspberrypi | 2023-07-09 21:05:46.371 | error | Caught by controller[0]: at Module._load (node:internal/modules/cjs/loader:958:12)
host.raspberrypi | 2023-07-09 21:05:46.370 | error | Caught by controller[0]: at Module.load (node:internal/modules/cjs/loader:1117:32)
host.raspberrypi | 2023-07-09 21:05:46.370 | error | Caught by controller[0]: at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
host.raspberrypi | 2023-07-09 21:05:46.370 | error | Caught by controller[0]: at Module._compile (node:internal/modules/cjs/loader:1254:14)
host.raspberrypi | 2023-07-09 21:05:46.370 | error | Caught by controller[0]: at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.enigma2/lib/utils.js:46:25)
host.raspberrypi | 2023-07-09 21:05:46.370 | error | Caught by controller[0]: at require (node:internal/modules/cjs/helpers:110:18)
host.raspberrypi | 2023-07-09 21:05:46.370 | error | Caught by controller[0]: at Module.require (node:internal/modules/cjs/loader:1141:19)
host.raspberrypi | 2023-07-09 21:05:46.370 | error | Caught by controller[0]: at Module._load (node:internal/modules/cjs/loader:920:27)
host.raspberrypi | 2023-07-09 21:05:46.369 | error | Caught by controller[0]: at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
host.raspberrypi | 2023-07-09 21:05:46.369 | error | Caught by controller[0]: - /opt/iobroker/node_modules/iobroker.enigma2/main.js
host.raspberrypi | 2023-07-09 21:05:46.369 | error | Caught by controller[0]: - /opt/iobroker/node_modules/iobroker.enigma2/lib/utils.js
host.raspberrypi | 2023-07-09 21:05:46.369 | error | Caught by controller[0]: Require stack:
host.raspberrypi | 2023-07-09 21:05:46.369 | error | Caught by controller[0]: Error: Cannot find module '/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js'
host.raspberrypi | 2023-07-09 21:05:46.369 | error | Caught by controller[0]: ^
host.raspberrypi | 2023-07-09 21:05:46.368 | error | Caught by controller[0]: throw err;
host.raspberrypi | 2023-07-09 21:05:46.368 | error | Caught by controller[0]: node:internal/modules/cjs/loader:1078
host.raspberrypi | 2023-07-09 21:05:45.334 | info | instance system.adapter.enigma2.0 started with pid 25001

</body>
</html>`

**Comment by mcm1957** [comment]
Please add version of major components
Adapter version:
Admin version:
js-controller version:
node version:
Operating system and version:

**Comment by Apollon77** [comment]
I assume an old version ... please install latest version from beta repository

**Comment by mcm1957** [comment]
Quite sure, thats why I asked for VERSION INFOS. Versioninfo is the minimum Info to add to EVERY problem issue...
Without this Info I will close here

**Comment by Michaelnorge** [comment]
I think that was the problem. thx!
