### ISSUE TITLE
STANDBY not updated correctly

### ISSUE THREAD

**Issue by kgerlich** [iobroker-community-adapters/ioBroker.enigma2#11]
Hi,

parseBool does not always parse correctly.

Changing to also filter \r works for me.

function parseBool(string){
    var cleanedString = string[0].replace(/(\r|\t\n|\n|\t)/gm,"");
    switch(cleanedString.toLowerCase()){
        case "true": case "yes": case "1": return true;
        default: return false;
    }
}

**Comment by Matten-Matten** [comment]
Okay, wenn das mit dem \r bei mir auch funktioniert, übernehme ich das im Adapter.
Vielen Dank für den Tip

Gruß
Matten Matten

**Comment by Matten-Matten** [comment]
abgeändert.

**Comment by kgerlich** [comment]
Danke!
