### ISSUE TITLE
Nach Adapter Neustart States werden nicht aktualisiert 

### ISSUE THREAD

**Issue by ww-os** [iobroker-community-adapters/ioBroker.enigma2#118]
Nach Update und Start des Enigma2-Adapters auf V 2.0.1 werden die States nicht aktualisiert bzw. initialisiert. Zustandsänderungen der Enigma2 Box werden nicht aktualisiert. Der State enigma2-CONNECTION hat den Wert false, obwohl die Box im Standby ist.
Nach einem Command STANDBY_TOGGLE=True oder False (unbestätigt) wird das Command von der Box angenommen und ausgeführt.
Der State enigma2-CONNECTION ist ab diesem Zeitpunkt true. Ab diesem Zeitpunkt werden offensichtlich dann die states dauerhaft aktualisiert.
Nach Stop/Start des Adapters funktioniert die Aktualisierung der States nicht mehr.
Der State enigma2-CONNECTION ist ab diesem Zeitpunkt wieder false.
Erst nach obiger Prozedur ist die Aktualisierung wieder aktiv.
Bei dieser Gelegenheit ist mir aufgefallen, dass z.B. das Command STANDBY_TOGGLE vom Adapter nach Ausführung nicht bestätigt wird und rot bleibt( könnte ein generelles Problem der Commands sein..

**Comment by mcm1957** [comment]
@GermanBluefox 
Kannst du dir das bitte ansehen. Du hats da ja gestern einige PRs gemerged. 
Ich hab mit 2.0.1 nur node requirments noch nachgezoigen.

**Comment by mcm1957** [comment]
closed on error

**Comment by mk176** [comment]
Habe das gleiche Problem,
Dreambox 7020HD.
Nach dem Update wird scheinbar keine Verbindung mehr hergestellt und im Log steht:

16.08.2023 20:07 | error | Cannot access   'state' before initialization
-- | -- | --
16.08.2023 20:07 | error | ReferenceError:   Cannot access 'state' before initialization at AdapterClass.<anonymous>   (C:\Program Files\iobroker\node_modules\iobroker.enigma2\main.js:208:52) at   AdapterClass.emit (node:events:514:28) at Immediate.<anonymous>   (C:\Program Files\iobroker\node_modules\@iobroker\js-controller-adapter\build\lib\adapter\adapter.js:8409:53)   at process.processImmediate (node:internal/timers:476:21)

16.08.2023 20:07 | error | unhandled   promise rejection: Cannot access 'state' before initialization

16.08.2023 20:07 | error | Unhandled   promise rejection. This error originated either by throwing inside of an   async function without a catch block, or by rejecting a promise which was not   handled with .catch().

**Comment by GermanBluefox** [comment]
Please retest with 2.0.2

**Comment by mk176** [comment]
Retested with 2.0.2.
The enigma2-connection state is not set to true. I have to set some command to enigma, then it is set to cennect and only then it starts polling the status of the enigma.

**Comment by mk176** [comment]
> Please retest with 2.0.2

error is gone in 2.0.2. But still same error as ww-os described

**Comment by ww-os** [comment]
Am Fehlerbild hat sich nichts geändert!

**Comment by muhagl** [comment]
Gleicher Fehler hier ...

**Comment by ihavenonick** [comment]
selber Fehler auf der DM Two mit AOI Image

**Comment by TDCroPower** [comment]
gleicher Fehler mit 2.0.2 mit Vu+ OpenATV 7.3

**Comment by fs-plugins** [comment]
auch ein aktiver Adapter aktualisiert keine states, nachdem die Box heruntergefahren ist
es genügt also der Verlust connection, damit der Adapter keine Reaktion mehr zeigt

2023-08-27 06:48:35.405 | info | starting.  Version 2.0.2 (non-npm: iobroker-community-adapters/ioBroker.enigma2)  in /opt/iobroker/node_modules/iobroker.enigma2, node: v18.17.1,  js-controller: 4.0.24
2023-08-27 06:48:35.573 | info | starting Polling every 5000 ms

danach (mit Protokoll 'Alles') keinerlei Reaktion mehr

es wurde iobroker, npm usw. aktualisiert, enigma2 (VTi, python2) wurde seit langer Zeit nicht verändert/aktualisiert

**Comment by fs-plugins** [comment]
Behelfslösung:

ich setze (bei Änderung Ping an die Box auf 'true') ein
`setStateDelayed("enigma2.0.main_command.WAKEUP_FROM_STANDBY",true,180*60*1000);`
edit: Zeit natürlich viel zu lang, zudem eignet sich anderer State besser:
`setStateDelayed("enigma2.0.enigma2.Update",true,3*60*1000);`

der Befehl bewirkt ein manuelles Auslösen der gesamten Abfrage und der Adapter läuft dann bis zum nächsten Connection-false problemlos durch

bei mir hat der Betriebszustand der Box in der Steuerung erheblichen Einfluss u.a. auf Raumtemperatur, Licht, Zusatzgeräte (AVR, Bassbox usw.), evtl. Rollo
deshalb ist es in der Steuerung essentiell, die anderen vom Adapter verfügbaren Infos sind ein liebgewonnenes Future

wäre schade wenn der Adapter nicht mehr angepasst wird, dann muss entweder auf den Boxen ein Senden der Infos oder ein eigenes script zur Abfrage realisiert werden

**Comment by mk176** [comment]
Found a solution in main.js, since i am not sure how to create a pull request, i hope @GermanBluefox can review and add it.

stating in line 1296.
**var first_time	=true;**
    eventInterval = setInterval(async () => {
        if (isConnected **|| first_time**) {
            let xml = await getResponseAsync('GETSTANDBY', deviceId, PATH['POWERSTATE']);
            await evaluateCommandResponse('GETSTANDBY', deviceId, xml);

            xml = await getResponseAsync('MESSAGEANSWER', deviceId, PATH['MESSAGEANSWER']);
            await evaluateCommandResponse('MESSAGEANSWER', deviceId, xml);

            xml = await getResponseAsync('GETINFO', deviceId, PATH['ABOUT']);
            await evaluateCommandResponse('GETINFO', deviceId, xml);

            xml = await getResponseAsync('GETVOLUME', deviceId, PATH['VOLUME']);
            await evaluateCommandResponse('GETVOLUME', deviceId, xml);

            xml = await getResponseAsync('GETCURRENT', deviceId, PATH['GET_CURRENT']);
            await evaluateCommandResponse('GETCURRENT', deviceId, xml);

            xml = await getResponseAsync('ISRECORD', deviceId, PATH['ISRECORD'],);
            await evaluateCommandResponse('ISRECORD', deviceId, xml);

            xml = await getResponseAsync('TIMERLIST', deviceId, PATH['TIMERLIST']);
            await evaluateCommandResponse('TIMERLIST', deviceId, xml);
        };
	**first_time=false;**
    }, adapter.config.PollingInterval);

**Comment by fs-plugins** [comment]
@mk176
thank you for the efforts

adapter start/restart -> it works
box-start from shutdown (state connection=false) -> it does not work

**Comment by reihd** [comment]
gleiche Probleme bei mir, einmal Box neu starten und keine States werden mehr aktualisiert

**Comment by mk176** [comment]
> @mk176 thank you for the efforts
> 
> adapter start/restart -> it works box-start from shutdown (state connection=false) -> it does not work

OK, found out, that the if clause if (isConnected) { in line 1297 is not nessesary. if you remove it it will work, also after box restart

**Comment by fs-plugins** [comment]
yes, it works
_don't forget the closing bracket "}"..._

P.S.
By the way, it would be very nice if standby on + standby off were not always reported when the box is restarted (GUI or completely).
I have to monitor the state standby with waiting times because, for example, the state changes when the box is restarted, even when it is switched off it remains on standby=true.

**Comment by Apollon77** [comment]
@mk176 Can you do a PR please for the relevant code change?

**Comment by TDCroPower** [comment]
I have created a PR from this...
https://github.com/iobroker-community-adapters/ioBroker.enigma2/pull/125

**Comment by Lucky-ESA** [comment]
Verstehe nicht warum ich im PR erwähnt wurde! Leider nutze ich diesen Adapter nicht mehr da ich mir einen eigenen geschrieben habe.
@mk176 
Hast du noch diesen Fehler (ReferenceError)? Wenn die Zeile 208 noch richtig ist, dann bitte in allen Datenpunkte im Ordner .message. das "null" ersetzen.
Wahrscheinlich läuft der Adapter dann wieder durch und sollte aktualisieren.

Gruß//Lucky

**Comment by mcm1957** [comment]
> Verstehe nicht warum ich im PR erwähnt wurde! Leider nutze ich diesen Adapter nicht mehr da ich mir einen eigenen geschrieben habe. 

@Lucky-ESA 
Sorry, 
Da dieser commit von vor 3 Wochen dich erwähnt, wollte ich nur sicherstellen, dass nix an dir vorbeigeht:
https://github.com/iobroker-community-adapters/ioBroker.enigma2/commit/ba5e6c8089eb454f0cb16e76ce4d7857811e922e

Wenn du den Adapter nicht mehr benutzt ist es natürlich auch OK. DANKE für deine bisherigen Beiträge.

**Comment by Lucky-ESA** [comment]
@mcm1957 Kein Problem. Wenn Hilfe benötigt wird kannst du mich immer erwähnen. Werde dich immer gerne unterstützen.

**Comment by TDCroPower** [comment]
Der Merge meines PR ist durch, wer nicht auf das Release warten will kann solange die aktuelle git Version per Katze installieren.
Nach dem Release einfach wieder "normal" installieren, damit die Update Funktion wieder gegeben ist.
Ansonsten einfach entspannt auf das nächste Release warten.

**Comment by mcm1957** [comment]
Sorry, missed the release step for unknown reason.
New version 2.0.3 should be available at latest this afternoon.
