### ISSUE TITLE
Warnung im 5000ms Zyklus

### ISSUE THREAD

**Issue by ww-os** [iobroker-community-adapters/ioBroker.enigma2#119]
Diese Warnung erfolgt im 5000ms Abrufintervall
2023-08-16 16:29:40.574  - [33mwarn[39m: enigma2.0 (10783) evaluateCommandResponse: TypeError: Cannot read properties of undefined (reading 'toString')
2023-08-16 16:29:45.623  - [33mwarn[39m: enigma2.0 (10783) evaluateCommandResponse: TypeError: Cannot read properties of undefined (reading 'toString')

**Comment by Krisiun666** [comment]
Ich habe den Enigma in Version Installierte Version:
2.0.3  Der Fehler bei mir heißt: <html><body>


enigma2.0 | 2023-09-17 20:45:15.511 | warn | evaluateCommandResponse: TypeError: Cannot read properties of undefined (reading 'toString')
-- | -- | -- | --



</body>
</html>
Weißt jemand ein Rat?

**Comment by Krisiun666** [comment]
<p dir="auto" data-x-bergamot-id="1"><font x-bergamot-sentence-index="0" x-bergamot-sentence-score="-0.240392"><font x-bergamot-word-index="0" x-bergamot-word-score="-0.141047">Ich</font> <font x-bergamot-word-index="1" x-bergamot-word-score="-0.194793">habe</font> <font x-bergamot-word-index="2" x-bergamot-word-score="-1.38235" class="x-fxtranslations-bad">den</font> <font x-bergamot-word-index="3" x-bergamot-word-score="-0.00734973">Enigma</font> <font x-bergamot-word-index="4" x-bergamot-word-score="-0.0182388">in</font> <font x-bergamot-word-index="5" x-bergamot-word-score="-0.0685185">Version</font> <font x-bergamot-word-index="6" x-bergamot-word-score="-0.0110055">Installierte</font> <font x-bergamot-word-index="7" x-bergamot-word-score="-0.0998353">Version:</font></font>
<br data-x-bergamot-id="2"><font x-bergamot-sentence-index="1" x-bergamot-sentence-score="-0.105317"><font x-bergamot-word-index="0" x-bergamot-word-score="-0.00366534">2.0.3</font> <font x-bergamot-word-index="1" x-bergamot-word-score="-0.00941291">Der</font> <font x-bergamot-word-index="2" x-bergamot-word-score="-0.00405573">Fehler</font> <font x-bergamot-word-index="3" x-bergamot-word-score="-0.172297">bei</font> <font x-bergamot-word-index="4" x-bergamot-word-score="-0.337153">mir:</font></font></p> 




<font x-bergamot-sentence-index="2" x-bergamot-sentence-score="-0.179069"><font x-bergamot-word-index="0" x-bergamot-word-score="-0.179069"></font></font><font x-bergamot-sentence-index="5" x-bergamot-sentence-score="-0.193886"><font x-bergamot-word-index="0" x-bergamot-word-score="-0.0714079"></font></font>

enigma2.0 | 2023-09-17 20:45:15.511 | warnen | evaluateCommandResponse: TypeError: Kann Eigenschaften von undefiniert nicht lesen (Lese 'toString')
-- | -- | -- | --









<font x-bergamot-sentence-index="6" x-bergamot-sentence-score="-0.438158"><font x-bergamot-word-index="0" x-bergamot-word-score="-0.00640123">Weißt</font> <font x-bergamot-word-index="1" x-bergamot-word-score="-1.15381" class="x-fxtranslations-bad">jemand</font> <font x-bergamot-word-index="2" x-bergamot-word-score="-0.529857">ein</font> <font x-bergamot-word-index="3" x-bergamot-word-score="-0.0625676">Rat?</font></font>

**Comment by mcm1957** [comment]
@ww-os 
Hast du ev. einen Aufnahme TIMER angelegt?

Kannst du bitte den Output von
```http://<deineip>/web/timerlist```

psoten - wobei deineip natürlcih durch die ip deiner box (111.222.333.444) zu ersetzen wäre.

Danke

P.S. Zusätzlich verrate uns bitte noch die installeiten Versionen
enigma2 adapter
js-controller

@Lucky-ESA

**Comment by Krisiun666** [comment]
Hallo, 
js-controller v. 5.0.12
enigma2 adapter v. 2.0.3

Output ohne aktiven Timer:

<e2timerlist>
<script id="__gaOptOutExtension"/>
</e2timerlist>

Output mit aktiven Timer:

<e2timerlist>
<script id="__gaOptOutExtension"/>
<e2timer>
<e2servicereference>1:0:19:C35C:2723:F001:FFFF0000:0:0:0:</e2servicereference>
<e2servicename>RTL HD</e2servicename>
<e2eit>5772</e2eit>
<e2name>Ulrich Wetzel - Das Jugendgericht</e2name>
<e2description>
Wurde Mutter einer Nachhilfeschülerin brutal von Leiter `gestoßen?`
</e2description>
<e2descriptionextended>
Als die Mutter ihrer Nachhilfeschülerin herausfindet, dass ihr Vater im Gefängnis sitzt, verliert Cindy Bauer ihren Job. Kurz darauf, wird Mutter Bettina bei der Gartenarbeit brutal von einer Leiter gestoßen - mit schmerzhaften Folgen.
</e2descriptionextended>
<e2disabled>0</e2disabled>
<e2timebegin>1695049020</e2timebegin>
<e2timeend>1695051310</e2timeend>
<e2duration>2290</e2duration>
<e2startprepare>1695049000</e2startprepare>
<e2justplay>0</e2justplay>
<e2afterevent>3</e2afterevent>
<e2location>/media/usb/movie/</e2location>
<e2tags/>
<e2logentries>
[(1695043024, 15, 'record time changed, start prepare is now: Mon Sep 18 16:56:40 2023')]
</e2logentries>
<e2filename/>
<e2backoff>0</e2backoff>
<e2nextactivation/>
<e2firsttryprepare>True</e2firsttryprepare>
<e2state>0</e2state>
<e2repeated>0</e2repeated>
<e2dontsave>0</e2dontsave>
<e2cancled>False</e2cancled>
<e2toggledisabled>1</e2toggledisabled>
<e2toggledisabledimg>off</e2toggledisabledimg>
<e2alwayszap>0</e2alwayszap>
<e2pipzap>0</e2pipzap>
</e2timer>
</e2timerlist>

Log Fehler:

<html><body>


enigma2.0 | 2023-09-18 15:18:16.058 | warn | evaluateCommandResponse: TypeError: Cannot read properties of undefined (reading 'toString')
-- | -- | -- | --



</body>
</html>

Villen Dank für die Hilfe 👍

**Comment by mcm1957** [comment]
fixed with 2.0.5
please retest
