### ISSUE TITLE
Add information = isRecording

### ISSUE THREAD

**Issue by joergzdarsky** [iobroker-community-adapters/ioBroker.enigma2#12]
Enigma2 devices from VU+ (such as VU+ UNO 4K SE) provide additional endpoints on top to enigma2 to get information about the current device status. Please add an option in the ioBroker enigma2 adapter to fetch the information from the statusinfo endpoint (if provided by device / optional) and provide it's information in the iobroker enigma2 Adapter and the object tree. 

Endpoint:
http://<host>/api/statusinfo

Example Response:
{"inStandby": "false", "currservice_begin": "16:05", "currservice_begin_timestamp": 1546614300, "currservice_end_timestamp": 1546621200, "muted": false, "isRecording": "false", "currservice_station": "Das Erste HD", "currservice_serviceref": "1:0:19:283D:3FB:1:C00000:0:0:0:", "currservice_description": "Handball-L\u00e4nderspiel: Deutschland-Tschechien", "volume": 85, "currservice_fulldescription": "Sportschau\n16:05 - 18:00\n\n* Reporter: Florian Na\u00df\n* Moderation: Alexander Bommes\n\n\u00dcbertragung aus Hannover", "currservice_name": "Sportschau", "currservice_filename": "", "transcoding": true, "currservice_end": "18:00", "currservice_id": 46296}

Of specific interest if you do not want to add the whole response would be the "isRecording" since it can be used to trigger further events within ioBroker (e.g. an Alexa hint).

**Comment by Matten-Matten** [comment]
- add: `.enigma2.isRecording` in enigma2 V1.2.1

**Comment by Matten-Matten** [comment]
![Bild Text](https://raw.githubusercontent.com/Matten-Matten/ioBroker.enigma2/master/admin/enigma2.png)

## Changelog
### 1.2.2 (2019-08-08)
* (Matten-Matten)       correction in `.enigma2.isRecording` check

Gruß
Matten Matten
