### ISSUE TITLE
Wunsch/Bitte

### ISSUE THREAD

**Issue by fs-plugins** [iobroker-community-adapters/ioBroker.enigma2#14]
Moin,
es wäre schön, wenn Gesamt- und Restzeit auch in Minuten als Datenpunkt vorliegen würden.
In Verbindung mit einem Bar-Widget wäre die Anzeige Gesamt- und Restminuten dann kleiner und intuitiver (natürlich ginge eine Umrechnung im script, jedoch wäre es so insgesamt schlanker)

**Comment by Matten-Matten** [comment]
done in V1.1.9
