### ISSUE TITLE
Adapter löschen

### ISSUE THREAD

**Issue by Shepherd7** [iobroker-community-adapters/ioBroker.enigma2#16]
Kann den Adapter aus der Adapter Übersicht vom ioBroker nicht löschen.
can´t delete the Adapter from Adapter list.

$ ./iobroker del enigma2
Delete adapter "enigma2"
host.iobroker no instances of adapter enigma2 found
host.iobroker Adapter enigma2 cannot be deleted completely, because non-deletable.
ERROR: process exited with code 22

**Comment by Matten-Matten** [comment]
unter
\iobroker\node_modules\iobroker.enigma2
Bzw.
/opt/iobroker/node_modules/iobroker.enigma2

einfach den enigma2 Ordner löschen.

**Comment by Shepherd7** [comment]
Habe den Adapter damals wie du geschrieben hast gelöscht.
Ordner einfach gelöscht unter /opt/iobroker/node_modules/iobroker.enigma2
dann ist enigma2 aus der Liste im iobroker weg, kommt aber nach einiger Zeit wieder und steht unter Adapter loiste drin.
Wie bekomme ich ihn komplett gelöscht so dass er nicht wieder automatisch in der Liste auftaucht?

**Comment by Matten-Matten** [comment]
Wenn alle Instanzen Entfernt wurden, und der Ordner enigma2 aus  /opt/iobroker/node_modules/
Gelöscht wurde taucht er nirgendwo mehr auf, das ist höchstens ein Webanzeige Problem. Dann am besten die Webseite im Browser aktualisieren
