### ISSUE TITLE
Enigma2 Set Top Box Status

### ISSUE THREAD

**Issue by funboxbolzer** [iobroker-community-adapters/ioBroker.enigma2#17]
Hallo zusammen, besteht die Möglichkeit, den Status vom Receiver (on/off) nicht via "Standby" zu steuern sonder einen separaten Status Trigger zu integrieren? Ich kenne diesen aus FHEM, da wird "on/off" im "STATE" wiedergegeben. 
Grund hierfür ist, das ich wie YAHKA einen Switch integrieren möchte, damit ich den Receiver an und ausschalten kann. Viele Grüße funboxbolzer

**Comment by Matten-Matten** [comment]
`enigma2.0.Alexa_Command.Standby`

![objects - ioBroker-24 04 2019_09_08_58](https://user-images.githubusercontent.com/32074970/56639309-b032cb80-6670-11e9-9991-312c3bee87af.jpg)
![instances - ioBroker-24 04 2019_09_10_16](https://user-images.githubusercontent.com/32074970/56639389-dbb5b600-6670-11e9-8f9b-5900a54e157d.jpg)

**Comment by funboxbolzer** [comment]
Danke erst mal für die schnelle antwort.
Leider ist das nicht das was ich benötige. Denn der Status wird nicht aktualisiert wenn ich die VU+ mit der Fernbedienung ein oder ausschalte.

**Comment by Matten-Matten** [comment]
Ah okay, ich schaue Mal ob ich das integriert bekomme.

**Comment by funboxbolzer** [comment]
Danke. Wäre echt top.

**Comment by Matten-Matten** [comment]
- feature #17 : `.Alexa_Command.Mute` & `.Alexa_Command.Standby` now with status feedback

 - add: `.enigma2.EVENT_TIME_PASSED`

**Comment by funboxbolzer** [comment]
Besten Dank. Funzt jetzt 1A.
