### ISSUE TITLE
enigma Adapter löschen

### ISSUE THREAD

**Issue by Shepherd7** [iobroker-community-adapters/ioBroker.enigma2#18]
Habe den Adapter damals wie du geschrieben hast gelöscht.
Ordner einfach gelöscht unter /opt/iobroker/node_modules/iobroker.enigma2
dann ist enigma2 aus der Liste im iobroker weg, kommt aber nach einiger Zeit wieder und steht unter Adapter loiste drin.
Wie bekomme ich ihn komplett gelöscht so dass er nicht wieder automatisch in der Liste auftaucht?

**Comment by Matten-Matten** [comment]
Bevor du den Adapter wie oben beschrieben aus den Ordner

> /opt/iobroker/node_modules

Gelöscht hast, hast du auch vorher die Adapter Instanz gelöscht?

**Comment by Shepherd7** [comment]
Ja habe ich schon paar mal gemacht.
Instanz läuft ja nicht nur unter Adapter kommt er immer wieder von alleine.
Nach dem löschen ist er ja weg, irgendwann ist er wieder da.
Habe aber noch nicht rausgefunden wann er wieder kommt.
Speichert iobroker noch irgendwas irgendwo in ner Liste und kommt wieder wenn ich repo update mache?

**Comment by Matten-Matten** [comment]
Bisher ist das bei keinem meiner iobroker Systeme aufgetreten, ich denke das ist ein iobroker Webbrowser Problem. Vielleicht Mal iobroker admin neu starten, und Browser Cache leeren

**Comment by Shepherd7** [comment]
Werde ich nochmal tun, Danke für deine Hilfe.
Muss mal genau beobachten ob nach paar tagen oder wochen der adapter in der liste wieder auftaucht
