### ISSUE TITLE
Seit 04.06.2019 funktioniert der Adapter nicht mehr

### ISSUE THREAD

**Issue by Nuggelbeb** [iobroker-community-adapters/ioBroker.enigma2#19]
Hallo, seit heute 04.06.2019 funktioniert der Adapter im IoBroker nicht mehr!

**Comment by Matten-Matten** [comment]
Ich brauche schon mehr Infos...
Debug Log,
System Infos....

**Comment by Matten-Matten** [comment]
Ich brauche schon mehr Infos...
Debug Log,
System Infos....

**Comment by Nuggelbeb** [comment]
host.ioBroker | 2019-06-04 17:14:01.376 | info | Restart adapter system.adapter.enigma2.1 because enabled
-- | -- | -- | --
host.ioBroker | 2019-06-04 17:14:01.376 | error | instance system.adapter.enigma2.1 terminated with code 1 ()
host.ioBroker | 2019-06-04 17:14:01.376 | error | Caught by controller[0]: at tryModuleLoad (module.js:506:12)
host.ioBroker | 2019-06-04 17:14:01.376 | error | Caught by controller[0]: at Module.load (module.js:566:32)
host.ioBroker | 2019-06-04 17:14:01.376 | error | Caught by controller[0]: at Object.Module._extensions..js (module.js:664:10)
host.ioBroker | 2019-06-04 17:14:01.375 | error | Caught by controller[0]: at Module._compile (module.js:653:30)
host.ioBroker | 2019-06-04 17:14:01.375 | error | Caught by controller[0]: at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.enigma2/node_modules/xml2js/lib/parser.js:357:4)
host.ioBroker | 2019-06-04 17:14:01.375 | error | Caught by controller[0]: at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.enigma2/node_modules/xml2js/lib/parser.js:9:9)
host.ioBroker | 2019-06-04 17:14:01.375 | error | Caught by controller[0]: at require (internal/module.js:11:18)
host.ioBroker | 2019-06-04 17:14:01.374 | error | Caught by controller[0]: at Module.require (module.js:597:17)
host.ioBroker | 2019-06-04 17:14:01.374 | error | Caught by controller[0]: at Function.Module._load (module.js:475:25)
host.ioBroker | 2019-06-04 17:14:01.374 | error | Caught by controller[0]: at Function.Module._resolveFilename (module.js:548:15)
host.ioBroker | 2019-06-04 17:14:01.374 | error | Caught by controller[0]: Error: Cannot find module 'sax'
host.ioBroker | 2019-06-04 17:14:01.373 | error | Caught by controller[0]: ^
host.ioBroker | 2019-06-04 17:14:01.373 | error | Caught by controller[0]: throw err;
host.ioBroker | 2019-06-04 17:14:01.366 | error | Caught by controller[0]: module.js:550

**Comment by Matten-Matten** [comment]
Hast du den Adapter Mal neu von GitHub geladen? Und  ein Upload gemacht?

**Comment by Nuggelbeb** [comment]
Nein, er funktionierte ja bis heute super.

**Comment by Matten-Matten** [comment]
Hast du das iobroker System geändert?

**Comment by Nuggelbeb** [comment]
Nein, nur ordentlich Adapter Updates gemacht.

**Comment by Matten-Matten** [comment]
ok. vielleicht einmal den Adapter löschen und wieder neu laden und einrichten.

**Comment by Nuggelbeb** [comment]
OK,
es ist eigenartig. Ich habe heute nichts gemacht, plötzlich geht der Adapter nicht mehr. ROT
Aber ich habe ihn deinstalliert mit Fehlermeldung "Code 22" danach Enigma 2 neu installiert und ein Upload gemacht. Gott sei Dank er geht wieder:

Danke
