### ISSUE TITLE
node_modules 

### ISSUE THREAD

**Issue by GermanBluefox** [iobroker-community-adapters/ioBroker.enigma2#2]
Why do you have node_modules?

And why the same packages in lib?

**Comment by Matten-Matten** [comment]
ich habe die selben Pakete in lib, da bei der Installation auf iobroker aus GitHub er den Ordner node_modules nicht mit kopiert hat. Da ich nicht wirklich Programmier Kenntnisse eines solchen Adapters babe hab ich mir so beholfen. Ich weiß auch nicht wie ich den gesamten  Ordner **_node_modules_** hier löschen kann. Sorry 

Würde ich das Programmieren hier beherrschen, dann hätte ich wahrscheinlich auch problemlos 
die **_Commands_**  
`https://github.com/Matten-Matten/ioBroker.enigma2/blob/master/admin/COMMAND`
im Adapter integrieren können.

Das was ich kann versuche ich ja irgendwie umzusetzen. Sorry. 
Mir fehlen da einfach die **Java** Kenntnisse.

Ich bräuchte jemand der sich damit auskennt und das umändert.

Gruß
Matten Matten

**Comment by Matten-Matten** [comment]
erledigt.
