### ISSUE TITLE
is recording ohne Funktion

### ISSUE THREAD

**Issue by guergen1** [iobroker-community-adapters/ioBroker.enigma2#20]
Hallo,

habe hier den Enigma2-Adapter mit einer VU Uno4k laufen.
Trotz gestarteter Aufnahme wird im Debug-Log "is recording false" angegeben.

**Comment by Matten-Matten** [comment]
Ist das nur im debug Log oder auch im wenn du das logen auf Info stellst?

**Comment by guergen1** [comment]
Der Receiver nimmt grade auf. Im Log steht gar nichts:
![grafik](https://user-images.githubusercontent.com/34395245/64863603-900ea380-d635-11e9-8b90-244ced7249d8.png)
Im Debug-Log folgendes:
![grafik](https://user-images.githubusercontent.com/34395245/64863664-b16f8f80-d635-11e9-8a82-cd673a1acb7e.png)
Und in den Objekten dieses: 
![grafik](https://user-images.githubusercontent.com/34395245/64863701-ccda9a80-d635-11e9-8d31-b98ec9835e80.png)

**Comment by Matten-Matten** [comment]
OK , scheinbar ein Einzelfall.

Könntest du bitte folgendes im Browser aufrufen, und die Antwort hier Posten?

Http://IP der Box:Port/web/timerlist

**Comment by guergen1** [comment]
<e2timer><e2servicereference>1:0:19:EF10:421:1:C00000:0:0:0:</e2servicereference><e2servicename>RTL HD</e2servicename><e2eit>13674</e2eit><e2name>Ran an den Speck - Familien nehmen ab</e2name><e2description/><e2descriptionextended>Acht Familien mit Übergewicht, 90 Tage Zeit und 10.000 Euro Gewinn. In der neuen Daytime-Sendung "Ran an den Speck - Familien nehmen ab" sagen acht Familien ihrem angefutterten Kilos den Kampf an....</e2descriptionextended><e2disabled>0</e2disabled><e2timebegin>1568380785</e2timebegin><e2timeend>1568384100</e2timeend><e2duration>3315</e2duration><e2startprepare>1568380765</e2startprepare><e2justplay>0</e2justplay><e2afterevent>3</e2afterevent><e2location>/media/net/Movies/</e2location><e2tags/><e2logentries>[(1568380785, 15, 'record time changed, start prepare is now: Fri Sep 13 15:19:25 2019'), (1568380785, 5, 'activating state 1'), (1568380785, 0, "Filename calculated as: '/media/net/Movies/RAN_AN_DEN_SPECK_-_FAMILIEN_NEHMEN_AB'"), (1568380785, 16, 'record event 10'), (1568380785, 16, 'record event 2'), (1568380785, 16, 'record event 6'), (1568380785, 6, 'prepare ok, waiting for begin'), (1568380785, 5, 'activating state 2'), (1568380785, 16, 'record event 0'), (1568380785, 16, 'record event 4'), (1568380785, 11, 'start recording'), (1568380785, 16, 'record event 9'), (1568380785, 16, 'record event 4'), (1568380785, 16, 'record event 6')]</e2logentries><e2filename>/media/net/Movies/RAN_AN_DEN_SPECK_-_FAMILIEN_NEHMEN_AB</e2filename><e2backoff>0</e2backoff><e2nextactivation>1568380785</e2nextactivation><e2firsttryprepare>True</e2firsttryprepare><e2state>2</e2state><e2repeated>0</e2repeated><e2dontsave>1</e2dontsave><e2cancled>False</e2cancled><e2toggledisabled>1</e2toggledisabled><e2toggledisabledimg>off</e2toggledisabledimg><e2alwayszap>-1</e2alwayszap></e2timer>

**Comment by guergen1** [comment]
Habe grade die Aufnahme gestartet... den Rest der Timer habe ich weggelassen...
Oder liegt´s am vergebenen Passwort?
Aktuell:
![grafik](https://user-images.githubusercontent.com/34395245/64865792-715edb80-d63a-11e9-956e-09f51e38e84b.png)

**Comment by Matten-Matten** [comment]
Ah ok, ja das liegt am Passwort, jedoch ist das ein Abfrage Fehler, ich werde das die Tage abändern! Sobald das geändert wurde werde ich das im Forum und hier Posten und das issuse schließen.

Gruß 
Matten Matten

**Comment by guergen1** [comment]
Perfekt!
Mittlerweile muss man ja ein Passwort vergeben, sonst sind andere Funktionen gesperrt...

**Comment by Matten-Matten** [comment]
### 1.2.3 (2019-09-15)
* (Matten-Matten)       authentication correction in `.enigma2.isRecording` check
* (Matten-Matten)       correction in `.enigma2.isRecording` check after shutdown
