### ISSUE TITLE
Entfernen der enigma2 v2.0.5 Instanz: SendTo Blockly nicht mehr wählbar

### ISSUE THREAD

**Issue by m4ding** [iobroker-community-adapters/ioBroker.enigma2#207]
Hi,

ich setze die aktuelle stable Version von javascript (7.8.0) ein. Ich habe die aktuelle Version des enigma2 Adapters installiert. Sobald ich diesen deinstalliere, kann ich kein sendTo in Blockly mehr wählen:
![grafik](https://github.com/iobroker-community-adapters/ioBroker.enigma2/assets/65028008/583495ee-e62a-4249-93f5-452d6c507542)

Sobald der Adapter wieder installiert ist, geht es wieder. 

Das Problem ist problemlos reproduzierbar (deinstallieren/ wieder installieren des enigma2 Adapters).

Ich benötige den Adapter nicht mehr und würde ihn gerne deinstallieren können.

Danke!

**Comment by mcm1957** [comment]
@klein0r 
Hast du da irgendeine Idee dazu? 

An sich wäre ja ein blockly Problem als Issue im Javascript Adapter zu behandeln. Ich hab keine Idee wieso das DEINSTALLIEREN eines Adapters blockly permanent stören kann. Der Adapter hat ja gar keinen besonderen "Deinstallationscode". Und wenn die Blockly Extension von Enigma entfernt ist sollte doch der javascript Adapter diese einfach nicht mehr anbieten ...

**Comment by klein0r** [comment]
> Hast du da irgendeine Idee dazu?

Ohne die Fehlermeldung aus der Browser-Console fällt mir dazu auch nichts ein.

**Comment by mcm1957** [comment]
@m4ding 
Bitte wie von klein0r angesprochen um einen Check der Browser-Console und das log

Und bitte sicherheitshalber nach der Deinstallation des Adapters auch mal browser cache löschen.

**Comment by m4ding** [comment]
es muss was damit zu tun haben, dass enigma ja auch ein sendto anbietet

![grafik](https://github.com/iobroker-community-adapters/ioBroker.enigma2/assets/65028008/f03616ea-e574-4c51-899c-74186af83637)

nach der Deinstallation des enigma2 Adapters, habe ich den sendto Bereich aufgerufen, hier die Ausgabe der Konsole, ich hoffe, das hilft:

`Nice to see you here! :) Join our dev community here https://github.com/ioBroker/ioBroker or here https://github.com/iobroker-community-adapters [Prompt.js:16:12](http://192.168.253.202:8081/adapter/javascript/static/node_modules/@iobroker/adapter-react-v5/Prompt.js)
Help us to create open source project with reactJS! [Prompt.js:17:12](http://192.168.253.202:8081/adapter/javascript/static/node_modules/@iobroker/adapter-react-v5/Prompt.js)
See you :) [Prompt.js:18:12](http://192.168.253.202:8081/adapter/javascript/static/node_modules/@iobroker/adapter-react-v5/Prompt.js)
[2024-02-20T09:10:29.965Z] Try to connect [socket.io.js:66:41](http://192.168.253.202:8081/lib/js/socket.io.js)
Detected custom blockly: awtrix-light [console.ts:40:19](http://192.168.253.202:8081/adapter/javascript/static/node_modules/@sentry/src/instrument/console.ts)
Detected custom blockly: enigma2 [console.ts:40:19](http://192.168.253.202:8081/adapter/javascript/static/node_modules/@sentry/src/instrument/console.ts)
Detected custom blockly: mqtt [console.ts:40:19](http://192.168.253.202:8081/adapter/javascript/static/node_modules/@sentry/src/instrument/console.ts)
Detected custom blockly: telegram [console.ts:40:19](http://192.168.253.202:8081/adapter/javascript/static/node_modules/@sentry/src/instrument/console.ts)
Translation for word "Sends message via telegram" in "de" was ignored: existing = "Sendet eine Nachricht per telegram", new = Sendet Nachricht per Telegramm [console.ts:40:19](http://192.168.253.202:8081/adapter/javascript/static/node_modules/@sentry/src/instrument/console.ts)
Translation for word "You can use %s in the text to display current trigger value or %id to display the triggered object ID" in "de" was ignored: existing = "Sie können %s im Text verwenden, um den aktuellen Triggerwert anzuzeigen, %id, um die ausgelöste Objekt-ID zu verwenden, %name, um den ID-Namen des ausgelösten Objekts anzuzeigen, oder %old, um den alten Triggerwert zu verwenden", new = Sie können %s im Text verwenden, um den aktuellen Triggerwert anzuzeigen, oder %id, um die ID des ausgelösten Objekts anzuzeigen [console.ts:40:19](http://192.168.253.202:8081/adapter/javascript/static/node_modules/@sentry/src/instrument/console.ts)
Calling the Mutator constructor without passing the block it is attached to was deprecated in version 9 and will be deleted in version 10.
Use the constructor by passing the list of subblocks and the block instance to attach the mutator to instead. [console.ts:40:19](http://192.168.253.202:8081/adapter/javascript/static/node_modules/@sentry/src/instrument/console.ts)
Calling the Icon constructor with a null block was deprecated in version 9 and will be deleted in version 10.
Use a non-null block instead. [console.ts:40:19](http://192.168.253.202:8081/adapter/javascript/static/node_modules/@sentry/src/instrument/console.ts)
Ignoring non-existent input TIMEOUT in block sendto_otherscript [console.ts:40:19](http://192.168.253.202:8081/adapter/javascript/static/node_modules/@sentry/src/instrument/console.ts)
Ignoring non-existent input STEP in block sendto_gethistory [console.ts:40:19](http://192.168.253.202:8081/adapter/javascript/static/node_modules/@sentry/src/instrument/console.ts)
Uncaught TypeError: FieldDropdown options must not be an empty array.
    validateOptions$$module$build$src$core$field_dropdown blockly_compressed.js:280
    FieldDropdown$$module$build$src$core$field_dropdown blockly_compressed.js:658
    init blockly.js:70
    doInit_ blockly_compressed.js:761
    BlockSvg$$module$build$src$core$block_svg blockly_compressed.js:901
    newBlock blockly_compressed.js:1662
    domToBlockHeadless$$module$build$src$core$xml blockly_compressed.js:182
    domToBlock$$module$build$src$core$xml blockly_compressed.js:172
    createFlyoutBlock_ blockly_compressed.js:1395
    createFlyoutInfo_ blockly_compressed.js:1393
    show blockly_compressed.js:1392
    updateFlyout_ blockly_compressed.js:1626
    setSelectedItem blockly_compressed.js:1625
    onClick_ blockly_compressed.js:1614
    g blockly_compressed.js:133
    r helpers.ts:98
[blockly_compressed.js:280:166](http://192.168.253.202:8081/adapter/javascript/google-blockly/blockly_compressed.js)
XHRPOST
[https://sentry.iobroker.net/api/56/envelope/?sentry_key=504499a725eb4898930d3b9e9da95740&sentry_version=7&sentry_client=sentry.javascript.browser/7.98.0](https://sentry.iobroker.net/api/56/envelope/?sentry_key=504499a725eb4898930d3b9e9da95740&sentry_version=7&sentry_client=sentry.javascript.browser%2F7.98.0)
[HTTP/2 403  59ms]

XHRPOST
[https://sentry.iobroker.net/api/56/envelope/?sentry_key=504499a725eb4898930d3b9e9da95740&sentry_version=7&sentry_client=sentry.javascript.browser/7.98.0](https://sentry.iobroker.net/api/56/envelope/?sentry_key=504499a725eb4898930d3b9e9da95740&sentry_version=7&sentry_client=sentry.javascript.browser%2F7.98.0)
[HTTP/2 403  55ms]

Source-Map-Fehler: Error: request failed with status 404
Ressourcen-Adresse: http://192.168.253.202:8081/adapter/javascript/google-blockly/blockly_compressed.js
Source-Map-Adresse: blockly_compressed.js.map`

**Comment by klein0r** [comment]
> nach der Deinstallation des enigma2 Adapters, habe ich den sendto Bereich aufgerufen

Dann dürfte aber eigentlich das hier nicht mehr auftauchen:

> Detected custom blockly: enigma2 [console.ts:40:19](http://192.168.253.202:8081/adapter/javascript/static/node_modules/@sentry/src/instrument/console.ts)

Oder hast Du nur die Instanz gelöscht, aber den Adapter weiterhin installiert?
Dann wäre es eventuell ein Bug im Blockly des enigma Adapters, dass er das Dropdown mit den Instanzen nicht füllen kann

**Comment by klein0r** [comment]
Ich denke das ist der Fall, denn dann wäre `options` leer - und das mag Blockly nicht:

https://github.com/iobroker-community-adapters/ioBroker.enigma2/blob/877b4a635b00b99bf6943720beba667dd501ca77/admin/blockly.js#L53-L70

**Comment by mcm1957** [comment]
@klein0r 
Ich hab keine Ahnung von Blockly. Wenn du Zeit hast und das fixen kannst sag ich DANKE. PR od commit der blockly Dateien.wär ausreichend, release kann ich dir genre abnehmen wenn dir das was hilft.

Ansonsten muss das Issue halt warten bis wer mit Blockly Kenntnissen das anschaun / antesten kann.

**Comment by m4ding** [comment]
@klein0r richtig, ich habe nur die Instanz gelöscht. Ich kann gerne den Adapter auch entfernen.

**Comment by m4ding** [comment]
ok, nach dem Entfernen des Adapters gehts wieder. Auf die Idee bin ich noch nicht gekommen.

**Comment by klein0r** [comment]
> Ich kann gerne den Adapter auch entfernen.

Na wozu behalten und weiterhin updates machen, wenn man den eh nicht mehr haben will? 😄

**Comment by m4ding** [comment]
warum einfach, wenns auch schwierig geht ;) bin einfach nicht auf die Idee gekommen :). Weg ist weg (Instanz ;I))

**Comment by klein0r** [comment]
> @m4ding Sobald ich diesen deinstalliere, kann ich kein sendTo in Blockly mehr wählen:

Bitte in Zukunft genauer sein bei den Beschreibungen. Du hattest den Adapter ja nicht deinstalliert. Sonst schickst Du uns hier in die falsche Richtung 👍 

Aber danke für den Report. @mcm1957 Mir fehlt da momentan die Zeit für (und das ist ja auch wirklich ein Edge-Case).

> Weg ist weg (Instanz ;I))

Naja, wenn Du ein Word-Dokument löschst, ist Word davon auch nicht deinstalliert...

**Comment by m4ding** [comment]
OK sorry, ja: wie geschrieben: bin nicht auf die Idee gekommen. Mache ich zukünftig. Danke für eure Hilfe!

Der Vergleich hinkt etwas, aber ich verstehe deinen Punkt 👍

**Comment by klein0r** [comment]
> Der Vergleich hinkt etwas

Naja, wenn Du nur die Instanz löschst, dann werden einfach nur ein paar Objekte im System entfernt. Alle Daten des Adapters im Dateisystem bleiben bestehen. Warum hinkt der Vergleich dann?

Du siehst ja, dass die Dateien alle noch bestehen bleiben - der Blockly-Block wäre ja auch noch da (wenn er nicht diesen Bug hätte).

**Comment by m4ding** [comment]
bei Adaptern von Git installiert man ja erst den Adapter und dann noch die Instanz. Wenn ich einen Adapter aus dem "Adapter" Tab installiere, dann ist dem ja nicht so, richtig? Daher habe ich wohl nicht dran gedacht.

**Comment by klein0r** [comment]
> Wenn ich einen Adapter aus dem "Adapter" Tab installiere, dann ist dem ja nicht so, richtig?

Dann wird auch der Adapter erst installiert (von npm). Nur wird in dem Fall automatisch eine Instanz erzeugt. Das Ergebnis ist genau das gleiche. Du hast trotzdem eine Adapter-Installation und eine Instanz mit der Konfiguration.

*Von Github installieren ist in 99% der Fälle aber eh eine schlechte Idee.*

**Comment by m4ding** [comment]
wie mache ich es besser, wenn der Adapter nicht im Adapter-Tab gelistet ist?

**Comment by klein0r** [comment]
> wie mache ich es besser, wenn der Adapter nicht im Adapter-Tab gelistet ist?

Das kommt drauf an, ob dieser schon eine definierte Version hat (auf npm) oder nicht und welches Repo Du nutzt. Würde hier jetzt den Rahmen sprengen und habe ich ja schon in diversen Video-Inhalten ausführlichst mit Beispielen erklärt. Was fehlt Dir da an Infos?

**Comment by m4ding** [comment]
ich schaue mal deine Videos danach durch. Ich arbeite schon einige Jahre mit iobroker, das scheint mir durch die Lappen gegangen zu sein. Danke für deine Unterstützung und auch generell für deinen Einsatz in dem Projekt!

**Comment by mcm1957** [comment]
> wie mache ich es besser, wenn der Adapter nicht im Adapter-Tab gelistet ist?

Wenn ein Adapter nicht im Repository gelistet ist solltest du zuerst mal seeehr vorsichtig sein.
Von einer Installation von Adaptern die nicht im Repository gelistet sind auf produktiven Systeme wird generell abgeraten. 

Natürlich kannst du - auf eigenes Risiko - einen neuen Adapter in Abstimmung mit dem DEV auch direkt von Github installieren. Aber bitte bedenke, dass der Softwarestand auf Github sich jederzeit ändern kann und die dort verfügbaren Versionsnummern nicht zwingend in Relation zu einem Softwarestand stehen. 

Prinzipiell solltest du (für produktive Systeme)
- Adapter vom STABLE repository installieren
- Adapter vom LATEST repository installieren wenn dort ein dringend benötigter Bugfix schon verfügbar ist und du ein gewisses Risiko einer Software im Beta Stadium tragen willst ("A working Backup is your friend")

Nur für Testsysteme oder experimentierfreudige User gilt:
- Adapter von NPM installieren (da gibts wenigestens einen definierten Stand)
- Adapter von Github installieren als allerletzte Wahl (und nur in Abstimmung mit dem Entwickler)

Wenn ein Entwickler mittel / langfristig seinen Adapter nicht in die Repos aufnehmen lässt sollte er darauf angesprochen werden (z.B. via Issue im Adapter repository). Oft (aber nicht immer) ist dies ein Indiz, dass der Adapter eine Art Quick Hack ist und nur mäßig gewartet wird. Die Aufnahme ins Repo kostet nichts - außer ev. ein paar Anpassungen wenn sich im Zuge des Reviews Anpassungsbedarf gezeigt hat.

mcm1957
