### ISSUE TITLE
Adapter Probleme bei Client Installation

### ISSUE THREAD

**Issue by LJSven** [iobroker-community-adapters/ioBroker.enigma2#21]
Der Adapter stürzt ab und startet neu. Memory ist genug vorhanden. Der Adapter ist auf einem Raspberry (via WLAN). Woran kann es liegen?

**Comment by Matten-Matten** [comment]
Ich brauche ein Log Auszug

**Comment by LJSven** [comment]
> 

  | 2019-09-28 03:41:30.748 | info | Restart adapter system.adapter.enigma2.0 because enabled
-- | -- | -- | --
host.raspberrypi | 2019-09-28 03:41:30.747 | error | instance system.adapter.enigma2.0 terminated with code 7 (Adapter already running)
h

**Comment by Matten-Matten** [comment]
Hast du Mal den js Controller neu gestartet?

**Comment by LJSven** [comment]
Ja, das Problem tritt schon länger auf und nur bei deinem Adapter. Soll ich mal auf debug stellen, oder kannst du da nichts erkennen?

**Comment by Matten-Matten** [comment]
Am besten den Adapter Mal rausschmeißen
Und neu von GitHub laden, dann ein Upload machen und eine Instanz hinzufügen. 

Sollte der Fehler immer noch auftreten, bitte den vollständigen fehlerlog des Adapter Posten. Und nein erstmal noch nicht auf debug stellen

**Comment by LJSven** [comment]
Okay, mache ich.

**Comment by LJSven** [comment]
Ich kann den Adapter nicht löschen - es kommt folgende Meldung ->

```

$ ./iobroker del enigma2
Delete adapter "enigma2"
host.raspberrypi Adapter enigma2 cannot be deleted completely, because it is marked non-deletable.
ERROR: process exited with code 22
```

PS. Auch wenn ich es manuell über die Console probiere.

**Comment by Matten-Matten** [comment]
Kannst du erstmal ignorieren. Hauptsache die Instanzen sind weg. Dann neu von GitHub laden

**Comment by LJSven** [comment]
Okay, erledigt. Wo ist da jetzt der Unterschied zu einem Update? Die Version etc. hatte ich schon am laufen. Es tritt auch nicht definiert auf.

**Comment by Matten-Matten** [comment]
Das liegt manchmal am vorher nicht ausgeführten Upload. Das sollte das System automatisch machen, jedoch scheint das System das nicht immer zu machen.

**Comment by Matten-Matten** [comment]
Aber der Adapter läuft jetzt?

**Comment by LJSven** [comment]
Habe es jetzt mal fast 2 Tage getest - der Adapter startet immer noch nach einer Zeit neu.

**Comment by Matten-Matten** [comment]
Welche js Controller Version verwendest du?

Schicke bitte ein vollständiges Log

**Comment by LJSven** [comment]
1.5.14 / was meinst du mit vollständiges Log? Das ist das was kommt -> 

![Bildschirmfoto 2019-09-30 um 09 21 21](https://user-images.githubusercontent.com/8560588/65857254-be91bb80-e363-11e9-9c4e-b015839529e5.png)

**Comment by LJSven** [comment]
Ich vermute, es hat etwas mit meinem Slave (via WLAN) zu tun.

**Comment by Matten-Matten** [comment]
Da stimmt etwas nicht mit deinem System, der Adapter wird vom Host neu gestartet. 

Das ist überhaupt nicht ratsam Host und Slave via WLAN zu verbinden. 

Vermutlich verliert der Host zum Slave sporadisch die Verbindung und startet anschließend den Adapter neu.

**Comment by LJSven** [comment]
Es laufen 10 anderen Adapter auf dem Slave ohne Probleme / selbst SQL wird auf dem Slave geloggt und läuft tadellos / ohne Abbrüche. Der einzige Adapter, der sich neustartet ist dieser.

**Comment by Matten-Matten** [comment]
Weitere Fragen bitte im Forum stellen.
https://forum.iobroker.net/topic/25112/enigma2-adapter-ab-v1-2-3

**Comment by Matten-Matten** [comment]
- (Adapter only runs on one host! with a client installation there's currently still problems.)
- (DE)(Adapter läuft nur auf einem Host! bei einer Client Installation gib's aktuell noch probleme.)

**Comment by Matten-Matten** [comment]
@LJSven 

Kannst du die aktuelle version nichmal testen?

**Comment by LJSven** [comment]
@Matten-Matten Ich habe immer noch das gleiche Problem - nachdem der Adapter neu gestartet wurde, geht alles - einen Tag später nicht mehr.

**Comment by LJSven** [comment]
@Matten-Matten Ehrlich Frage, ehrliche Antwort: Glaubst du, du bekommst die Master-, Slave- Problematik in den Griff? Kann ich dir dabei helfen? Ansonsten würde ich auf eine Alternative umsteigen.

**Comment by Matten-Matten** [comment]
Ich habe es bisher noch nicht geschafft das Thema intensiv anzugehen. Sry.

Gruß
Matten Matten

**Comment by LJSven** [comment]
Ich habe 3 Dinge geändert und habe den Eindruck, daß es seitdem läuft.

1.) Umstieg von WLAN auf LAN
2.) Update js-controller 2.7.7
3.) iQontrol deaktivert

IQontrol habe ich schon ein paar Tage länger deaktivert - wenn ich ehrlich bin, habe ich den Eindruck, daß es daran lag. Kann das aber nicht sicher sagen und will es auch nicht "schlecht" reden.  Ich kenne mich zu wenig aus, als das ich behaupten kann, dass es da eine Verknüpfung gibt.

**Comment by Matten-Matten** [comment]
ok, dann liegt es nicht am adapter und ich kann das issue schließen?

**Comment by LJSven** [comment]
Ob es an deinem Adapter, oder an dem vom Kollegen, kann ich nicht beurteilen.

**Comment by Matten-Matten** [comment]
Sobald ich Zeit habe teste ich den Adapter auf eine iobroker Client. Dann sehe ich ja ob das Problem bei mir auch Auftritt.
