### ISSUE TITLE
FeatureRequest: Timer

### ISSUE THREAD

**Issue by MikeHotel0815** [iobroker-community-adapters/ioBroker.enigma2#23]
Is it possible to check, if a Timer is set? I would like to send the Box to DeepStandBy if ther is no timer, or even switch of the socket. ;)

Regards
Mike

**Comment by Matten-Matten** [comment]
das kann ich integrieren, wenn ich das Timer auslesen wieder einbaue.

**Comment by Matten-Matten** [comment]
done.

**Comment by MikeHotel0815** [comment]
Vielen Dank!
