### ISSUE TITLE
Feature Request: timer list

### ISSUE THREAD

**Issue by Scrounger** [iobroker-community-adapters/ioBroker.enigma2#25]
@Matten-Matten 

Super Adapter, hätte noch folgenden Wunsch :)

Könntest du noch die [TimerList](https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/wiki/OpenWebif-API-documentation#timerlist) implementieren?
Am besten wäre ein JSON String in [folgendem Format](https://github.com/Scrounger/ioBroker.vis-materialdesign#input-data), damit man die Infos in einem 'table widget' im VIS verwenden kann.

Super wären auch noch Datenpunkten wie zum nächsten Timer - Startzeit, ChannelName, ChannelRefName, Program infos, etc.

**Comment by Scrounger** [comment]
TimerListe hab ich kurz selbst implementiert -> PR #26.

**Comment by Matten-Matten** [comment]
Super vielen Dank!
habs gerade eingefügt, jedoch steigt der adapter jetzt aus wenn die Timerliste leer ist...

`

enigma2.0 | 2019-11-17 17:48:04.895 | info | (17800) Terminated (NO_ERROR): Without reason
-- | -- | -- | --
enigma2.0 | 2019-11-17 17:48:04.893 | info | (17800) terminating
enigma2.0 | 2019-11-17 17:48:04.334 | error | at process._tickCallback (internal/process/next_tick.js:68:7)
enigma2.0 | 2019-11-17 17:48:04.334 | error | at promise.then (/usr/local/addons/hm-iobroker/node_modules/standard-as-callback/built/index.js:19:49)
enigma2.0 | 2019-11-17 17:48:04.334 | error | at tryCatcher (/usr/local/addons/hm-iobroker/node_modules/standard-as-callback/built/utils.js:11:23)
enigma2.0 | 2019-11-17 17:48:04.334 | error | at client.get (/usr/local/addons/hm-iobroker/node_modules/iobroker.js-controller/lib/states/statesInRedis.js:483:33)
enigma2.0 | 2019-11-17 17:48:04.334 | error | at /usr/local/addons/hm-iobroker/node_modules/iobroker.enigma2/enigma2.js:684:27
enigma2.0 | 2019-11-17 17:48:04.334 | error | (17800) TypeError: Cannot read property 'val' of null
enigma2.0 | 2019-11-17 17:48:04.333 | error | (17800) uncaught exception: Cannot read property 'val' of null
enigma2.0 | 2019-11-17 17:48:03.471 | info | (17800) enigma2 Verbunden!
enigma2.0 | 2019-11-17 17:47:58.377 | info | (17800) starting Polling every 5000 ms
enigma2.0 | 2019-11-17 17:47:58.316 | info | (17800) starting. Version 1.2.4 in /usr/local/addons/hm-iobroker/node_modules/iobroker.enigma2, node: v10.16.3

`

**Comment by Scrounger** [comment]
oh stimmt, hab gar keine prüfung drin, ob es überhaupt daten gibt ;)
Werd ich fixen und nochmal nen PR machen

**Comment by Matten-Matten** [comment]
perfekt!

**Comment by Scrounger** [comment]
fix in #28

**Comment by Matten-Matten** [comment]
fonktioniert super 1000 Dank!

**Comment by Matten-Matten** [comment]
su scheinst in der Adapter Bau Materie sehr gut drin zu stecken, vielleicht Kannst du mir ja helfen  wenn es deine zeit hergibt. 
https://forum.iobroker.net/topic/26035/ben%C3%B6tige-hilfe-bei-enigma2-adapter-erweiterung

Gruß 
Matten
