### ISSUE TITLE
Message Objekte ready only

### ISSUE THREAD

**Issue by Biker58** [iobroker-community-adapters/ioBroker.enigma2#273]
Seit Adapterversion 2.2.1 sind die 3 Objekte unter Message als ready only gekennzeichnet. Dadurch kommt bei jeder versandten Nachricht eine Warnmeldung im Log.

Adapter 2.2.1
Node ja v20.18.1
NPM 10.8.2
js Controller 7.0.5

**Comment by mcm1957** [comment]
- please specify which objects you refer to.
- please attach a log showing error mrssage

cha gelog does not show any code change lately. Did you update js-controller at the same time?

**Comment by Biker58** [comment]
Es betrifft die Objekte im Verzeichnis Message


[Bild]

08.12.2024 23:59:46 Martin M. ***@***.***>:

**Comment by mcm1957** [comment]
Bitte keine Antworten per Mail. MIt dem Text (!) Bild kann ich nichts anfangen.
Bitte direkt auf der GitHub Webseite kommentieren bzw. Infos einfügen.

**Comment by Biker58** [comment]
Nodejs 20.18.1
NPM 10.8.2
js controller 7.0.6
enigma2 Adapter 2.2.1
![Screenshot 2024-12-09 at 11-56-15 objects - raspberrypi-5-iobroker](https://github.com/user-attachments/assets/020dcd3e-a133-4091-9976-20ac0d8ff8d4)
![Screenshot 2024-12-09 at 11-57-33 logs - raspberrypi-5-iobroker](https://github.com/user-attachments/assets/69e882b2-a5ff-4f3e-8ce4-8b5f62adff48)

**Comment by KallAdam** [comment]
Fehler kann ich bestätigen, über Objekte können keine Nachrichten angestoßen werden.
enigma2.0.Message.Text
enigma2.0.Message.Timeout
enigma2.0.Message.Type

Nachrichtenversand über Blockly funktioniert mit Fehlermeldung: 

2024-12-18 22:33:06.772 - info: javascript.0 (6120) Stopping script script.js.Test
2024-12-18 22:33:06.825 - info: javascript.0 (6120) Start JavaScript script.js.Test (Blockly)
2024-12-18 22:33:06.832 - info: javascript.0 (6120) script.js.Test: registered 0 subscriptions, 0 schedules, 0 messages, 0 logs and 0 file subscriptions
2024-12-18 22:33:06.846 - warn: enigma2.2 (6405) Read-only state "enigma2.2.Message.Text" has been written without ack-flag with value "test"

**Comment by denjo1982** [comment]
ja selbe problem hier, objekte sind schreibgeschützt

**Comment by mcm1957** [comment]
fixed with 2.2.2
