### ISSUE TITLE
Veröffentlichen auf npm

### ISSUE THREAD

**Issue by Scrounger** [iobroker-community-adapters/ioBroker.enigma2#29]
@Matten-Matten 

Kannst du deinen Adapter mal bei npm offziell veröffentlichen?
Dann bekommt man iobroker direkt mit wenn es eine neue version gibt.

**Comment by Matten-Matten** [comment]
Moin, 
Sobald ich Zeit finde werde ich mich Mal durchwursteln, wie ich das auf npm bekomme. Habe aber im Moment leider keine Zeit dafür. Bin da auch kein Developer wie du. Falls die Motivation hoch bei dir ist?, den Adapter weiter zu entwickeln kann ich dich gerne irgendwie zum Schirmherr des Adapters machen.

**Comment by Scrounger** [comment]
Veröffentlichung bei npm ist sehr einfach:

1. Account anlegen bei [npm](https://www.npmjs.com/)
2. User und password [per npm setzen](https://docs.npmjs.com/cli/adduser)
3. `npm install` im Verzeichnis des adapters ausführen
4. `npm publish` im Verzeichnis des adapters ausführen

Zumr Schirmherr fehlt mir leider die Zeit, kann dich aber gerne bei der Entwicklung unterstützen.

Dazu müsstest du mich bei github als Collaborators eintragen über settings -> Collaborators 
Und bei npm, einloggen in die seite, auf dein package gehen, über reiter 'admin' unter dem punkt 'Invite maintainer' meinen Namen eintragen

**Comment by Matten-Matten** [comment]
https://www.npmjs.com/package/iobroker.enigma2
