### ISSUE TITLE
MovieList hinzugefügt

### ISSUE THREAD

**Issue by Scrounger** [iobroker-community-adapters/ioBroker.enigma2#30]
@Matten-Matten 
So erste Amtshandlung als Vize ;-)

Hab die Funktion hinzugefügt, dass er alle Aufnahmen von der Box holt.
Diese Funktion wird allerdings nur alle 5min ausgeführt, da ich bedenken bzgl. der last bei großen Movie Sammlungen habe.

weiter hab ich mal den code formatiert, dass er die json api verarbeiten kann und eine funktion, um die getResponse async ausführen zu können -> macht das coden übersichtlicher ohne diese ganzen callback Verschachtelungen.

Teste mal bitte ob ich da noch einen fehler drin habe.

**Comment by Matten-Matten** [comment]
```
2019-11-26 18:17:58.613 - info: host.ioBroker instance system.adapter.enigma2.0 started with pid 2408
2019-11-26 18:17:59.028 - error: Caught by controller[0]: C:\ioBroker\node_modules\iobroker.enigma2\enigma2.js:271
2019-11-26 18:17:59.031 - error: Caught by controller[0]: async function getResponseAsync(deviceId, path) {
2019-11-26 18:17:59.032 - error: Caught by controller[0]: ^^^^^^^^
2019-11-26 18:17:59.032 - error: Caught by controller[0]:
2019-11-26 18:17:59.032 - error: Caught by controller[0]: SyntaxError: Unexpected token function
2019-11-26 18:17:59.032 - error: Caught by controller[0]: at createScript (vm.js:56:10)
2019-11-26 18:17:59.033 - error: Caught by controller[0]: at Object.runInThisContext (vm.js:97:10)
2019-11-26 18:17:59.033 - error: Caught by controller[0]: at Module._compile (module.js:542:28)
2019-11-26 18:17:59.033 - error: Caught by controller[0]: at Object.Module._extensions..js (module.js:579:10)
2019-11-26 18:17:59.034 - error: Caught by controller[0]: at Module.load (module.js:487:32)
2019-11-26 18:17:59.034 - error: Caught by controller[0]: at tryModuleLoad (module.js:446:12)
2019-11-26 18:17:59.034 - error: Caught by controller[0]: at Function.Module._load (module.js:438:3)
2019-11-26 18:17:59.034 - error: Caught by controller[0]: at Module.runMain (module.js:604:10)
2019-11-26 18:17:59.034 - error: Caught by controller[0]: at run (bootstrap_node.js:383:7)
2019-11-26 18:17:59.035 - error: Caught by controller[0]: at startup (bootstrap_node.js:149:9)
2019-11-26 18:17:59.035 - error: host.ioBroker instance system.adapter.enigma2.0 terminated with code 1 ()
2019-11-26 18:17:59.035 - info: host.ioBroker Restart adapter system.adapter.enigma2.0 because enabled
2019-11-26 18:18:00.316 - info: host.ioBroker instance system.adapter.ical.0 started with pid 3064

```

**Comment by Scrounger** [comment]
Hast du nodejs >= 8?

**Comment by Matten-Matten** [comment]
```
Betriebssystem
Windows
Architektur
x64
CPUs
4
Geschwindigkeit
1094 MHz
Modell
Intel(R) Celeron(R) CPU N3450 @ 1.10GHz
RAM
7.85 GB
System Betriebszeit
11 T. 02:20:27
Node.js
v6.11.4 (Es gibt eine neuere Version: v6.17.1 - Recommended version v10.17.0)
Anzahl der Adapter
260
Festplatte Größe
57.27 GB
Festplatte frei
30.09 GB
NPM
v3.10.10
Betriebszeit
00:13:20
Aktive Instanzen
10
```

**Comment by Scrounger** [comment]
Ja das ist das Problem. Du brauchst nodejs am besten in der version 8.16.2.

**Comment by Matten-Matten** [comment]
ok dann sollten wir das auch in der readme erwähnen und bitte dran denken, das der Adapter weiterhin beide Webinterfaces bedienen kann, openweb if und dream webif

**Comment by Matten-Matten** [comment]
also muss ich jetzt nodejs erst aktualisieren. :(

**Comment by Matten-Matten** [comment]
musste ich irgendwas beachten wenn ich jetzt nodejs aktualisiere?

**Comment by Scrounger** [comment]
nur den richtigen installer herunterladen, also auf version achten. am besten updatest gleich auf die iobroker empfohlene verison 10.17.0

**Comment by Matten-Matten** [comment]
host.ioBroker | 2019-11-26 19:08:57.282 | error | Caught by controller[1]: at process._tickCallback (internal/process/next_tick.js:63:19)
-- | -- | -- | --
host.ioBroker | 2019-11-26 19:08:57.282 | error | Caught by controller[1]: at endReadableNT (_stream_readable.js:1143:12)
host.ioBroker | 2019-11-26 19:08:57.282 | error | Caught by controller[1]: at IncomingMessage.emit (events.js:203:15)
host.ioBroker | 2019-11-26 19:08:57.282 | error | Caught by controller[1]: at IncomingMessage.<anonymous> (C:\ioBroker\node_modules\iobroker.enigma2\enigma2.js:331:24)
host.ioBroker | 2019-11-26 19:08:57.281 | error | Caught by controller[1]: at JSON.parse (<anonymous>)
host.ioBroker | 2019-11-26 19:08:57.281 | error | Caught by controller[1]: SyntaxError: Unexpected token < in JSON at position 1
host.ioBroker | 2019-11-26 19:08:57.281 | error | Caught by controller[0]: at process._tickCallback (internal/process/next_tick.js:63:19)
host.ioBroker | 2019-11-26 19:08:57.281 | error | Caught by controller[0]: at endReadableNT (_stream_readable.js:1143:12)
host.ioBroker | 2019-11-26 19:08:57.280 | error | Caught by controller[0]: at IncomingMessage.emit (events.js:203:15)
host.ioBroker | 2019-11-26 19:08:57.280 | error | Caught by controller[0]: at IncomingMessage.<anonymous> (C:\ioBroker\node_modules\iobroker.enigma2\enigma2.js:331:24)
host.ioBroker | 2019-11-26 19:08:57.280 | error | Caught by controller[0]: at JSON.parse (<anonymous>)
host.ioBroker | 2019-11-26 19:08:57.279 | error | Caught by controller[0]: SyntaxError: Unexpected token < in JSON at position 1
enigma2.0 | 2019-11-26 19:08:56.859 | error | (8596) SyntaxError: Unexpected token < in JSON at position 1 at JSON.parse (<anonymous>) at IncomingMessage.<anonymous> (C:\ioBroker\node_modules\iobroker.enigma2\enigma2.js:331:24) at Inc
enigma2.0 | 2019-11-26 19:08:56.858 | error | (8596) uncaught exception: Unexpected token < in JSON at position 1
enigma2.0 | 2019-11-26 19:08:56.677 | info | (8596) Terminated (NO_ERROR): Without reason
enigma2.0 | 2019-11-26 19:08:56.676 | info | (8596) terminating
enigma2.0 | 2019-11-26 19:08:56.182 | info | (8596) updating movie list
enigma2.0 | 2019-11-26 19:08:56.171 | error | (8596) SyntaxError: Unexpected token < in JSON at position 1 at JSON.parse (<anonymous>) at IncomingMessage.<anonymous> (C:\ioBroker\node_modules\iobroker.enigma2\enigma2.js:331:24) at Inc
enigma2.0 | 2019-11-26 19:08:56.170 | error | (8596) uncaught exception: Unexpected token < in JSON at position 1
enigma2.0 | 2019-11-26 19:08:55.183 | info | (8596) updating movie list
enigma2.0 | 2019-11-26 19:08:55.145 | info | (8596) enigma2 Verbunden!

**Comment by Matten-Matten** [comment]
also mit dem open web if kommen keine fehler, mit dream webif kommen die obigen fehler

**Comment by Matten-Matten** [comment]
ok warum auch immer jetzt kommen keine fehler mehr.

**Comment by Scrounger** [comment]
ok, hab trotzdem nochmal was eingebaut um parsing errors abzufangen.
Wo finde ich denn die aktuelle doku zu der dream webif api

**Comment by Matten-Matten** [comment]
https://dream.reichholf.net/wiki/Webinterface

**Comment by Matten-Matten** [comment]
https://dream.reichholf.net/wiki/Webinterface

**Comment by Matten-Matten** [comment]
im prinzip geht alles nicht was mit /api/ geholt werden kann.

**Comment by Matten-Matten** [comment]
entweder baut man in der config eine auswahl des jeweiligen verwendeten zur auswahl, oder man lässt alles mit /api/ weg....

**Comment by Matten-Matten** [comment]
jetzt hatte ich es wieder...

```

host.ioBroker | 2019-11-26 19:23:36.189 | info | instance system.adapter.enigma2.0 terminated with code 0 (NO_ERROR)
-- | -- | -- | --
host.ioBroker | 2019-11-26 19:23:36.189 | error | Caught by controller[0]: at process._tickCallback (internal/process/next_tick.js:63:19)
host.ioBroker | 2019-11-26 19:23:36.188 | error | Caught by controller[0]: at endReadableNT (_stream_readable.js:1143:12)
host.ioBroker | 2019-11-26 19:23:36.188 | error | Caught by controller[0]: at IncomingMessage.emit (events.js:203:15)
host.ioBroker | 2019-11-26 19:23:36.188 | error | Caught by controller[0]: at IncomingMessage.<anonymous> (C:\ioBroker\node_modules\iobroker.enigma2\enigma2.js:331:24)
host.ioBroker | 2019-11-26 19:23:36.188 | error | Caught by controller[0]: at JSON.parse (<anonymous>)
host.ioBroker | 2019-11-26 19:23:36.187 | error | Caught by controller[0]: SyntaxError: Unexpected token < in JSON at position 1
enigma2.0 | 2019-11-26 19:23:35.599 | info | (14316) Terminated (NO_ERROR): Without reason
enigma2.0 | 2019-11-26 19:23:35.597 | info | (14316) terminating
enigma2.0 | 2019-11-26 19:23:35.089 | error | (14316) SyntaxError: Unexpected token < in JSON at position 1 at JSON.parse (<anonymous>) at IncomingMessage.<anonymous> (C:\ioBroker\node_modules\iobroker.enigma2\enigma2.js:331:24) at In
enigma2.0 | 2019-11-26 19:23:35.088 | error | (14316) uncaught exception: Unexpected token < in JSON at position 1


```

**Comment by Matten-Matten** [comment]
hast du eine vu oder dream?

**Comment by Matten-Matten** [comment]
ich hab dein  catch parsing errors nochmal geladen jetzt kommt folgendes:


```
host.ioBroker | 2019-11-26 19:39:33.113 | info | Restart adapter system.adapter.enigma2.0 because enabled
-- | -- | -- | --
host.ioBroker | 2019-11-26 19:39:33.113 | error | instance system.adapter.enigma2.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
host.ioBroker | 2019-11-26 19:39:33.112 | error | Caught by controller[8]: at Function.Module._load (internal/modules/cjs/loader.js:585:3)
host.ioBroker | 2019-11-26 19:39:33.112 | error | Caught by controller[8]: 12)
host.ioBroker | 2019-11-26 19:39:33.112 | error | Caught by controller[7]: at tryModuleLoad (internal/modules/cjs/loader.js:593:
host.ioBroker | 2019-11-26 19:39:33.112 | error | Caught by controller[7]: d (internal/modules/cjs/loader.js:653:32)
host.ioBroker | 2019-11-26 19:39:33.112 | error | Caught by controller[6]: at Module.loa
host.ioBroker | 2019-11-26 19:39:33.112 | error | Caught by controller[6]: at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
host.ioBroker | 2019-11-26 19:39:33.112 | error | Caught by controller[6]: 78:30)
host.ioBroker | 2019-11-26 19:39:33.111 | error | Caught by controller[5]: er.js:7
host.ioBroker | 2019-11-26 19:39:33.111 | error | Caught by controller[4]: at Module._compile (internal/modules/cjs/load
host.ioBroker | 2019-11-26 19:39:33.111 | error | Caught by controller[4]: 2\enigma2.js:10:16)
host.ioBroker | 2019-11-26 19:39:33.111 | error | Caught by controller[3]: onymous> (C:\ioBroker\node_modules\iobroker.enigma
host.ioBroker | 2019-11-26 19:39:33.111 | error | Caught by controller[2]: at Object.<an
host.ioBroker | 2019-11-26 19:39:33.111 | error | Caught by controller[2]: at require (internal/modules/cjs/helpers.js:25:18)
host.ioBroker | 2019-11-26 19:39:33.111 | error | Caught by controller[2]: js/loader.js:692:17)
host.ioBroker | 2019-11-26 19:39:33.110 | error | Caught by controller[1]: at Module.require (internal/modules/c
host.ioBroker | 2019-11-26 19:39:33.110 | error | Caught by controller[1]: at Function.Module._load (internal/modules/cjs/loader.js:562:25)
host.ioBroker | 2019-11-26 19:39:33.110 | error | Caught by controller[1]: at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
host.ioBroker | 2019-11-26 19:39:33.110 | error | Caught by controller[1]: Error: Cannot find module 'xml2js'
host.ioBroker | 2019-11-26 19:39:33.110 | error | Caught by controller[1]:
host.ioBroker | 2019-11-26 19:39:33.110 | error | Caught by controller[0]: ^
host.ioBroker | 2019-11-26 19:39:33.110 | error | Caught by controller[0]: throw err;
host.ioBroker | 2019-11-26 19:39:33.109 | error | Caught by controller[0]: internal/modules/cjs/loader.js:638


```

**Comment by Matten-Matten** [comment]
und nochmal ich :)

alles gelöscht und Adapter neu von git installiert:


```
nigma2.0 | 2019-11-26 20:00:38.155 | info | (5840) enigma2 Verbunden!
-- | -- | -- | --
enigma2.0 | 2019-11-26 20:00:32.379 | info | (5840) starting Polling every 5000 ms
enigma2.0 | 2019-11-26 20:00:32.347 | info | (5840) starting. Version 1.2.5 in C:/ioBroker/node_modules/iobroker.enigma2, node: v10.17.0
host.ioBroker | 2019-11-26 20:00:29.348 | info | instance system.adapter.enigma2.0 started with pid 5840
host.ioBroker | 2019-11-26 20:00:09.596 | info | instance system.adapter.ical.0 terminated with code 0 (NO_ERROR)
host.ioBroker | 2019-11-26 20:00:00.043 | info | instance system.adapter.ical.0 started with pid 7376
host.ioBroker | 2019-11-26 19:59:59.321 | info | Restart adapter system.adapter.enigma2.0 because enabled
host.ioBroker | 2019-11-26 19:59:59.321 | info | instance system.adapter.enigma2.0 terminated with code 0 (NO_ERROR)
host.ioBroker | 2019-11-26 19:59:59.321 | error | Caught by controller[0]: at process._tickCallback (internal/process/next_tick.js:63:19)
host.ioBroker | 2019-11-26 19:59:59.321 | error | Caught by controller[0]: at endReadableNT (_stream_readable.js:1143:12)
host.ioBroker | 2019-11-26 19:59:59.321 | error | Caught by controller[0]: at IncomingMessage.emit (events.js:203:15)
host.ioBroker | 2019-11-26 19:59:59.320 | error | Caught by controller[0]: at IncomingMessage.<anonymous> (C:\ioBroker\node_modules\iobroker.enigma2\enigma2.js:337:49)
host.ioBroker | 2019-11-26 19:59:59.320 | error | Caught by controller[0]: ReferenceError: err is not defined
enigma2.0 | 2019-11-26 19:59:58.753 | info | (1472) Terminated (NO_ERROR): Without reason
enigma2.0 | 2019-11-26 19:59:58.751 | info | (1472) terminating
enigma2.0 | 2019-11-26 19:59:58.234 | error | at process._tickCallback (internal/process/next_tick.js:63:19)
enigma2.0 | 2019-11-26 19:59:58.234 | error | at endReadableNT (_stream_readable.js:1143:12)
enigma2.0 | 2019-11-26 19:59:58.234 | error | at IncomingMessage.emit (events.js:203:15)
enigma2.0 | 2019-11-26 19:59:58.234 | error | at IncomingMessage.<anonymous> (C:\ioBroker\node_modules\iobroker.enigma2\enigma2.js:337:49)
enigma2.0 | 2019-11-26 19:59:58.234 | error | (1472) ReferenceError: err is not defined
enigma2.0 | 2019-11-26 19:59:58.233 | error | (1472) uncaught exception: err is not defined
```
erst kommt der Fehler dann startet der Adapter erneut und danach kommen keine mehr....
auch auf meiner andern box,
vermutlich immer wenn er die movielist holt

**Comment by Scrounger** [comment]
Ok da war noch ein fehler drin, hab nochmal was hochgeladen.

Ich selber hab ne vu.

Problem ist, dass die 'web' api nicht die bookmarks mitliefert und man somit nicht alle movies bekommt aus allen unterordner. 
Das geht natürlich nicht mit der dream. Von daher ist dein vorschlag eine Auswahl in der Config einzubauen, wahrscheinlich die beste Lösung. D.h. aber auch, dass manche Funktionen mit der dream halt einfach nicht gehen.

**Comment by Matten-Matten** [comment]
wenn du selbst was an deiner box testen willst, musst du einfach das plugin webinterface installieren. das findet man in der vti plugin liste.

**Comment by Scrounger** [comment]
??? 
Teste doch mit meiner box und der OpenWebif API

**Comment by Matten-Matten** [comment]
geladen und gestartet mit folgenden error:


  |   |   |  
-- | -- | -- | --
enigma2.0 | 2019-11-26 20:31:01.207 | error | (5836) [getResponse] stack: SyntaxError: Unexpected token < in JSON at position 1 at JSON.parse (<anonymous>) at IncomingMessage.<anonymous> (C:\ioBroker\node_modules\iobroker.enigma2\enigma2.
enigma2.0 | 2019-11-26 20:31:01.207 | error | (5836) [getResponse] error: Unexpected token < in JSON at position 1
enigma2.0 | 2019-11-26 20:31:01.192 | error | (5836) [getResponse] stack: SyntaxError: Unexpected token < in JSON at position 1 at JSON.parse (<anonymous>) at IncomingMessage.<anonymous> (C:\ioBroker\node_modules\iobroker.enigma2\enigma2.
enigma2.0 | 2019-11-26 20:31:01.191 | error | (5836) [getResponse] error: Unexpected token < in JSON at position 1
enigma2.0 | 2019-11-26 20:31:01.176 | error | (5836) [getResponse] stack: SyntaxError: Unexpected token < in JSON at position 1 at JSON.parse (<anonymous>) at IncomingMessage.<anonymous> (C:\ioBroker\node_modules\iobroker.enigma2\enigma2.
enigma2.0 | 2019-11-26 20:31:01.175 | error | (5836) [getResponse] error: Unexpected token < in JSON at position 1
enigma2.0 | 2019-11-26 20:31:01.160 | error | (5836) [getAllMovies] stack: TypeError [ERR_UNESCAPED_CHARACTERS]: Request path contains unescaped characters at new ClientRequest (_http_client.js:115:13) at request (http.js:42:10) at Ob
enigma2.0 | 2019-11-26 20:31:01.159 | error | (5836) [getAllMovies] dir: /media/hdd/movie/neue Filme/, error: Request path contains unescaped characters
enigma2.0 | 2019-11-26 20:31:01.155 | error | (5836) [getResponse] stack: SyntaxError: Unexpected token < in JSON at position 1 at JSON.parse (<anonymous>) at IncomingMessage.<anonymous> (C:\ioBroker\node_modules\iobroker.enigma2\enigma2.
enigma2.0 | 2019-11-26 20:31:01.154 | error | (5836) [getResponse] error: Unexpected token < in JSON at position 1
enigma2.0 | 2019-11-26 20:31:01.139 | error | (5836) [getResponse] stack: SyntaxError: Unexpected token < in JSON at position 1 at JSON.parse (<anonymous>) at IncomingMessage.<anonymous> (C:\ioBroker\node_modules\iobroker.enigma2\enigma2.
enigma2.0 | 2019-11-26 20:31:01.139 | error | (5836) [getResponse] error: Unexpected token < in JSON at position 1
enigma2.0 | 2019-11-26 20:31:01.025 | error | (5836) [getResponse] stack: SyntaxError: Unexpected token < in JSON at position 1 at JSON.parse (<anonymous>) at IncomingMessage.<anonymous> (C:\ioBroker\node_modules\iobroker.enigma2\enigma2.
enigma2.0 | 2019-11-26 20:31:01.023 | error | (5836) [getResponse] error: Unexpected token < in JSON at position 1

**Comment by Scrounger** [comment]
Ok aber der adapter startet nicht mehr neu. Ist das die dream oder vu.
Die fehlermeldung dürfte jetzt nur noch bei der dream kommen.

**Comment by Matten-Matten** [comment]
das "webinterface" ist im prinzip das dream webif

hab beides installiert open webif und dream webif nur auf unterschiedlichen Ports

![Matze's VU+ Duo2 - OpenWebif-26 11 2019_20_34_53](https://user-images.githubusercontent.com/32074970/69666332-60940280-108c-11ea-9281-52c5d6c94e56.png)

**Comment by Scrounger** [comment]
ah ok das werd ich dann mal machen.

Dann wäre mein Vorschlag in der Config eine Auswahl für openwebif api und dream api zu implementieren, damit man gezielt die ansprechen kann.
Kannst du das einbauen?

**Comment by Matten-Matten** [comment]
![Matze's VU+ Duo2 - OpenWebif-26 11 2019_20_38_03](https://user-images.githubusercontent.com/32074970/69666630-da2bf080-108c-11ea-80da-96ca686fec10.png)
![Matze's VU+ Duo2 - OpenWebif-26 11 2019_20_39_07](https://user-images.githubusercontent.com/32074970/69666631-da2bf080-108c-11ea-98ce-d03b8b73e7a9.png)

**Comment by Matten-Matten** [comment]
kann ich machen

**Comment by Matten-Matten** [comment]
habs als true false  eingebaut, ist das so ok?

```
<option value="true" class="translate">OpenWebif</option>
<option value="false" class="translate">Dream-Webinterface</option>
```
![instances - ioBroker-26 11 2019_20_52_18](https://user-images.githubusercontent.com/32074970/69667649-b2d62300-108e-11ea-9e9b-735d019c7f4b.png)

**Comment by Matten-Matten** [comment]
ich habe es jetzt auch in enigma2.js eingefügt. ob es dort richtig ist musst du entscheiden wo genau du das haben möchtest. hat zumindest keine Fehler mehr ausgespuckt.

**Comment by Matten-Matten** [comment]
hatte zwischen drin auch mal folgenden Fehler:
```

enigma2.0 | 2019-11-26 22:28:39.227 | error | at process._tickCallback (internal/process/next_tick.js:68:7)
-- | -- | -- | --
enigma2.0 | 2019-11-26 22:28:39.227 | error | at evaluateCommandResponse (C:\ioBroker\node_modules\iobroker.enigma2\enigma2.js:747:14)
enigma2.0 | 2019-11-26 22:28:39.227 | error | at getAllMovies (C:\ioBroker\node_modules\iobroker.enigma2\enigma2.js:802:22)
enigma2.0 | 2019-11-26 22:28:39.227 | error | at getResponseAsync (C:\ioBroker\node_modules\iobroker.enigma2\enigma2.js:274:9)
enigma2.0 | 2019-11-26 22:28:39.227 | error | at new Promise (<anonymous>)
enigma2.0 | 2019-11-26 22:28:39.227 | error | at Promise (C:\ioBroker\node_modules\iobroker.enigma2\enigma2.js:275:3)
enigma2.0 | 2019-11-26 22:28:39.227 | error | at getResponse (C:\ioBroker\node_modules\iobroker.enigma2\enigma2.js:308:17)
enigma2.0 | 2019-11-26 22:28:39.227 | error | at Object.get (http.js:46:13)
enigma2.0 | 2019-11-26 22:28:39.227 | error | at request (http.js:42:10)
enigma2.0 | 2019-11-26 22:28:39.227 | error | at new ClientRequest (_http_client.js:115:13)
enigma2.0 | 2019-11-26 22:28:39.227 | error | (7360) [getAllMovies] stack: TypeError [ERR_UNESCAPED_CHARACTERS]: Request path contains unescaped characters
enigma2.0 | 2019-11-26 22:28:39.223 | error | (7360) [getAllMovies] dir: /media/hdd/movie/neue Filme/, error: Request path contains unescaped characters

```

**Comment by Scrounger** [comment]
Bug fix für den fehler ist hochgeladen.

Hab noch die Abfrage bzgl. apis verschoben. Implementierung für die dramapi mach ich die tage mal.

**Comment by Matten-Matten** [comment]
ok fehler kommt keiner mehr dafür 

```

enigma2.0 | 2019-11-27 16:33:56.777 | info | (1652) updating movie list
-- | -- | -- | --
enigma2.0 | 2019-11-27 16:33:49.406 | info | (1652) updating movie list
enigma2.0 | 2019-11-27 16:33:43.878 | info | (1652) updating movie list
enigma2.0 | 2019-11-27 16:33:38.424 | info | (1652) updating movie list
enigma2.0 | 2019-11-27 16:33:35.968 | info | (1652) updating movie list
enigma2.0 | 2019-11-27 16:33:29.860 | info | (1652) updating movie list
enigma2.0 | 2019-11-27 16:33:25.102 | info | (1652) updating movie list
enigma2.0 | 2019-11-27 16:33:19.839 | info | (1652) updating movie list
enigma2.0 | 2019-11-27 16:33:13.238 | info | (1652) updating movie list


```
und das Objekt **enigma2.0.enigma2.Movie_list** bleibt leer...

**Comment by Scrounger** [comment]
Hab nochmal ein bug fix hochgeladen. Für die openwebif api sollte es jetzt gehen

**Comment by Matten-Matten** [comment]
ok ich hab im forum eine anfrage bekommen die Messagebox zu integrieren, hab soweit auch was geschrieben.... eben wieder mit meinem begrenzten java Wissen ...

kannst ja mal drüberschauen.

```
// Some message was sent to adapter instance over message box. Used by email, pushover, text2speech, ...
adapter.on('message', function (obj) {
	if (obj !== null && obj !== undefined) {
    adapter.log.info('enigma2 message: ' + JSON.stringify(obj.message));
	var message_split = (JSON.stringify(obj.message)).split(":");
	
	var MESSAGE_TIMEOUT = message_split[0].replace(/"/g, '').slice(1);
	adapter.log.info('enigma2 message Timeout: ' + message_split[0].replace(/"/g, '').slice(1));
	adapter.setState('Message.Timeout', { val: MESSAGE_TIMEOUT, ack: true });
	
	var MESSAGE_TYPE = (JSON.stringify(obj.command)).replace(/"/g, '');/*.slice(0, -1), encodeURIComponent(MESSAGE_TEXT)*/
	adapter.log.info('enigma2 command Message Type: ' + MESSAGE_TYPE);
	adapter.setState('Message.Type', { val: MESSAGE_TYPE, ack: true });
	
	var MESSAGE_TEXT = message_split[1].replace(/"/g, '').slice(0, -1);
	adapter.log.info('enigma2 message Text: ' + message_split[1].replace(/"/g, '').slice(0, -1));
	adapter.setState('Message.Text', { val: MESSAGE_TEXT, ack: false });
		
	}
});
```

![javascript - ioBroker-enigma2 message](https://user-images.githubusercontent.com/32074970/69758542-154b2400-1160-11ea-819d-e17cad0a4906.png)

**Comment by Matten-Matten** [comment]
aus log.info hab ich log.debug aber gemacht.

**Comment by Matten-Matten** [comment]
keine fehler mehr aber das Objekt enigma2.0.enigma2.Movie_list bleibt leer...

**Comment by Scrounger** [comment]
geh mal in die settings, änder da was damit du speichern und neustarten kannst.
Liegt dran weil für 'adapter.config.Webinterface' kein standardwert hinterlegt ist.
Das muss man glaub noch in der package datei machen

**Comment by Matten-Matten** [comment]
Ja stimmt, dachte In der index.html reichte das...

**Comment by Scrounger** [comment]
> ok ich hab im forum eine anfrage bekommen die Messagebox zu integrieren, hab soweit auch was geschrieben.... eben wieder mit meinem begrenzten java Wissen ...
> 
> kannst ja mal drüberschauen.


wie sieht denn der sendTo befehl aus, um die funktion aufzurufen?
Auf die schnelle würde ich sagen das du das Objekt viel zu umständlich zerlegst, das geht sicher wesentlich einfach, hängt aber vom sendTo befehl ab

**Comment by Scrounger** [comment]
```
sendTo("enigma2", {
        message: 'nachricht',
        timeout: 30,
        msgType: info
    });
```

damit könntest du das dann viel einfacher aufrufen mit:
```
obj.message
obj.timeout
obj.msgType
```

dann sparst dir das ganze replace, slice, etc

**Comment by Matten-Matten** [comment]
```
sendTo("enigma2", {
        message: 'nachricht',
        timeout: 30,
        msgType: info
    });
```

ja klar aber wo baut man das ein in der io-package.json?

**Comment by Scrounger** [comment]
ne das wäre der befehl den man in einem javascript verwenden würde, um eine nachricht an den adapter zu schicken.

**Comment by Matten-Matten** [comment]
hmm ok....

**Comment by Matten-Matten** [comment]
dann im prinzip so.... ich schreibe das dazu und bei neuer offizieller version dann nur noch so wie du vorgeschlagen hast.

```
adapter.on('message', function (obj) {
	if (obj !== null && obj !== undefined) {

		adapter.log.debug('enigma2 message Timeout: ' + obj.timeout);
		adapter.setState('Message.Timeout', { val: obj.timeout, ack: true });
	
		adapter.log.debug('enigma2 command Message Type: ' + obj.msgType);
		adapter.setState('Message.Type', { val: obj.msgType, ack: true });
	
		adapter.log.debug('enigma2 message Text: ' + obj.message);
		adapter.setState('Message.Text', { val: obj.message, ack: false });	
	}
});
```

**Comment by Matten-Matten** [comment]
oder ich ändere das gleich ab. dann muss ich da nicht nochmal ran.

Ich kann kaum ausdrücken wie sehr du mir hilfst, GROßEN DANK!!!

**Comment by Matten-Matten** [comment]
sendTo("enigma2", {
        message: 'nachricht',
        timeout: 30,
        msgType: info
    });

das geht dann aber nur über java nicht über den Blockly  sendTo Block oder?

**Comment by Scrounger** [comment]
doch müsste auch mit blocky gehen, da es z.B. beim pushover adapter auch geht.
Ich hab aber selber keine ahnung von blocky.

**Comment by Matten-Matten** [comment]
der Pushover Adapter hat aber einen eigenen Block! 

![javascript - ioBroker-27 11 2019_23_05_06](https://user-images.githubusercontent.com/32074970/69762401-64965200-116a-11ea-9e19-97205305f26c.png)

**Comment by Matten-Matten** [comment]
vermutlich muss man da am Blockly entwickler anmelden...

**Comment by Scrounger** [comment]
hier ist ein beispiel wie man das blocky element implementieren kann:
https://github.com/ioBroker/ioBroker.pushover/blob/master/admin/blockly.js

Und hier ist beschrieben, wie es gehen könnte ohne ein extra blocky element:
https://forum.iobroker.net/topic/20845/wunschliste-blockly-elemente/11

**Comment by Matten-Matten** [comment]
https://github.com/Matten-Matten/ioBroker.enigma2/blob/master/admin/blockly.js

und den eintrag in io-package.json gemacht , der Block taucht aber nicht auf...

**Comment by Matten-Matten** [comment]
aber man kann es immer noch so machen
![javascript - ioBroker-enigma2 message](https://user-images.githubusercontent.com/32074970/69805532-225c2780-11e1-11ea-9245-6e5ccf11a6a8.png)

```
adapter.on('message', function (obj) {
	if (obj !== null && obj !== undefined) {
		adapter.log.debug('enigma2 message: ' + JSON.stringify(obj.message));
		
		adapter.log.debug('enigma2 message Timeout: ' + parseFloat(JSON.stringify(obj.message.timeout).replace(/"/g, '')));
		adapter.setState('Message.Timeout', { val: parseFloat(JSON.stringify(obj.message.timeout).replace(/"/g, '')), ack: true });
	
		adapter.log.debug('enigma2 command Message Type: ' + parseFloat(JSON.stringify(obj.message.msgType).replace(/"/g, '')));
		adapter.setState('Message.Type', { val: parseFloat(JSON.stringify(obj.message.msgType).replace(/"/g, '')), ack: true });
	
		adapter.log.debug('enigma2 message Text: ' + JSON.stringify(obj.message.message).replace(/"/g, ''));
		adapter.setState('Message.Text', { val: JSON.stringify(obj.message.message).replace(/"/g, ''), ack: false });	
	}
});
```

**Comment by Matten-Matten** [comment]
Moin, 
sag mal die _**async function**_ kann das zum erhöhten auslasten des Receivers kommen?

[Forum](https://forum.iobroker.net/topic/25112/test-adapter-enigma2-v1-2-x/176)

**Comment by Matten-Matten** [comment]
Ich habe jetzt eine auswahl ob timer und aufnahmen geladen werden sollen integriert.

![extras](https://user-images.githubusercontent.com/32074970/69900723-48b3cb80-1377-11ea-9c38-0bbe5eef23d3.png)

sowie den Picon Pfad als Objekt , bei aktiviertem Openwebif hinzugefügt.
