### ISSUE TITLE
Javascript-Blockly nicht mehr funktionsfähig

### ISSUE THREAD

**Issue by guergen1** [iobroker-community-adapters/ioBroker.enigma2#31]
Habe Probleme mit Blockly, man hat mir mitgeteilt, dass es sich um Probleme mit dem Enigma2-Adapter handeln soll:

https://github.com/ioBroker/ioBroker.admin/issues/474

(Siehe auch hier: https://forum.iobroker.net/topic/27219/gel%C3%B6st-skripte-im-blockly-sind-ausgeblendet/26)
Aktuelle Enigma-Adapter-Version 1.2.8

**Comment by Matten-Matten** [comment]
Ich schaue mir das nachher Mal an.

**Comment by BuZZy1337** [comment]
@Matten-Matten ich habe mir mal erlaubt das anzusehen da die Issues in mehreren Adaptern erstellt wurden und auch im Forum schon aufgetaucht sind..
Hinter Zeile 32 sowie 36 fehlt ```</value>```
https://github.com/Matten-Matten/ioBroker.enigma2/blob/a718d7967b530eedcece67a835f7e2bf9edc5082/admin/blockly.js#L26-L44

Bitte dringend beheben. 😉 

Gruß

**Comment by Matten-Matten** [comment]
danke für den Tip ! wird sofort erledigt!

**Comment by Matten-Matten** [comment]
eledigt

**Comment by guergen1** [comment]
Also kann ich den Enigma-Adapter aus github jetzt probieren?

**Comment by Matten-Matten** [comment]
Ja

**Comment by BuZZy1337** [comment]
Ja. Damit funktioniert es.. Gerade selbst getestet mit Firefox. :+1:

**Comment by guergen1** [comment]
Ja, läuft!
Danke!
