### ISSUE TITLE
Adapter im latest veröffenltichen

### ISSUE THREAD

**Issue by Scrounger** [iobroker-community-adapters/ioBroker.enigma2#32]
Hey @Matten-Matten ,

nach dem dein Adapter jetzt bei npm ist, wäre es noch super wenn der im latest repository verfügbar ist. Alle notwendigen Infos dazu findest du hier:
https://github.com/ioBroker/ioBroker.repositories

Ich kann das aber auch für Dich übernehmen, wenn du einverstanden bist?

**Comment by Matten-Matten** [comment]
Ich habs ja schon versucht.... bin aber gescheitert... wenn du noch kurz wartest würde ich noch was abändern dann auf npm übertragen.

**Comment by Scrounger** [comment]
Ja mach ich, allerdings muss vor veröffenltich eh die punkte aus #15 abgearbeitet werden.
Musst dir mal überlegen welche Lizenz du nehmen willst, bzw. kann das auch für dich machen.

**Comment by Matten-Matten** [comment]
ja davon hast du sicher mehr Ahnung. 
MIT  oder so?

**Comment by Scrounger** [comment]
hab alles soweit gemacht, siehe #15

**Comment by Matten-Matten** [comment]
hab alles auf npm übertragen.
