### ISSUE TITLE
Movielist erzeugt hohe last an Boxen

### ISSUE THREAD

**Issue by Scrounger** [iobroker-community-adapters/ioBroker.enigma2#33]
Movielist erzeugt hohe Laste an Boxen:
https://forum.iobroker.net/topic/25112/test-adapter-enigma2-v1-2-x/175

**Comment by Scrounger** [comment]
Hab da jetzt mal was eingebaut in 20d2d2a9bffc78899de270318b235cbffcb75fb8

Bitte teste des mal, weil bei mir das keinen Einfluss auf die Last hat.

**Comment by Matten-Matten** [comment]
ok ich teste

**Comment by Matten-Matten** [comment]
ich würde schon sagen das es sich verbessert hat

**Comment by Scrounger** [comment]
Ist es akzeptabel? Kann die wirst Zeiten auch noch erhöhen, bzw man könnte das auch in die settings aufnehmen

**Comment by Matten-Matten** [comment]
Ich denke das ist akzeptabel. Wir können es ja bei der nächsten Version mit in den settings nehmen
