### ISSUE TITLE
[Request]Enigmalight

### ISSUE THREAD

**Issue by BlueEssi** [iobroker-community-adapters/ioBroker.enigma2#34]
Es wäre super, wenn die Steuerung des Enigmalight-Addons in den Adapter integriert werden könnte.
Das Addon hat standardmäßig eine Webschnittstelle auf Port 1414 aktiv. Für mich wäre die Steuerung der Variablen "On/off Lights" und evtl. noch "Dynamic/Mood-Mode" interessant, um z.B. in Abhängigkeit von iobroker-Stati das "Ambilight" ein- bzw. auszuschalten.

**Comment by Matten-Matten** [comment]
Da enigmalight keine Funktion vom Webinterface ist und sicher nicht jeder das Enigmalight-Addon nutzt, wird das nicht in diesem Adapter integriert. Ich denke da sollte man über einem eigenständigen Adapter für Enigmalight nachdenken, ähnlich wie [Hyperion](https://github.com/ruhigundrelaxed/ioBroker.hyperion).
Ich selbst nutze enigmalight nicht sondern Hyperion, Kann daher auch keine Erfahrungen teilen, aber vieleicht solltest du das mit java-Blockly realisieren über Webanfragen und Befehle. dabei kannst du ja den enigma2 Adapter für IP nutzen.
