### ISSUE TITLE
Blocky send Message bei Windowsinstallation fehlt

### ISSUE THREAD

**Issue by funboxbolzer** [iobroker-community-adapters/ioBroker.enigma2#35]
Hallo, ich habe den Adapter auf Win und auf einem Raspberry Pi.
Beide haben die selbe  Versionsnummer und auch vom JavaAdapter sind die versionen identisch.
Bei Windows fehlt der Blockly Send Message Block. Ist das richtig so? Vielen Dank. Klaus

**Comment by Matten-Matten** [comment]
Das liegt eventuell an deiner js Controller Version

https://github.com/ioBroker/ioBroker.js-controller/issues/539

**Comment by funboxbolzer** [comment]
Ah. Bei der version 2.1.1 geht es nicht. 
Bei 1.5.1.4 geht es. Kann ich da dann was machen oder muss ich abwarten bis es funktioniert? Danke für die schnelle Antwort 😉

**Comment by Matten-Matten** [comment]
Ja du musst das
`type:     'adapter'`
Einfügen.
![Screenshot_20200102_223435](https://user-images.githubusercontent.com/32074970/71694829-9d9c9480-2db0-11ea-9556-101d52a96187.jpg)

![Screenshot_20200102_223546](https://user-images.githubusercontent.com/32074970/71694845-abeab080-2db0-11ea-8908-1ec8b4d52168.jpg)


![Screenshot_20200102_223347](https://user-images.githubusercontent.com/32074970/71694760-704fe680-2db0-11ea-83e7-c8e992b1d45f.jpg)

**Comment by funboxbolzer** [comment]
bei mir sieht es so aus...
<img width="300" alt="Bildschirmfoto 2020-01-03 um 04 17 55" src="https://user-images.githubusercontent.com/49862965/71705454-25e65e00-2de0-11ea-8d05-c7985cc2c4f3.png">
muss ich das "instance" ersetzen oder drin lassen? 

ich sehe noch, dass ich bei dem funktionierenden die Version 1.2.3 vom Adapter habe. bei dem es nicht funktioniert ist 1.2.9 installiert.

bei der 1.2.3 ist auch kein type: Adapter in der config.

**Comment by Matten-Matten** [comment]
du kannst es auch wie folgt lösen [ -> Blockly Import](https://github.com/Matten-Matten/ioBroker.enigma2/blob/master/admin/Blockly_Import.md)

**Comment by funboxbolzer** [comment]
Vielen Dank!!. Werde ich probieren.
