### ISSUE TITLE
isRecording ohne Funktion wenn Passwort Sonderzeichen beinhaltet 

### ISSUE THREAD

**Issue by dodo-dk** [iobroker-community-adapters/ioBroker.enigma2#36]
Hallo, vorerst vielen Dank für diesen Adapter.

Mir ist aufgefallen, dass der Datenpunkt "isRecording" nicht funktioniert, wenn der Receiver ein Passwort vergeben hat, der ein Sonderzeichen beinhaltet wie z.B. ein "?".

Entweder steht kein State dran, oder es bleibt immer auf false. Mit einem Passwort ohne Sonderzeichen funktioniert es.

Zudem wird der "isRecording" Datenpunkt ständig aktualisiert, obwohl der Receiver im DeepStandby ist, alle anderen Datenpunkte sind ok.

Webinterface: OWIF 1.2.8

Gruß Dodo

**Comment by Matten-Matten** [comment]
wenn ein timer erstellt aber deaktiviert ist, soll  dann 'enigma2.Timer_is_set' auf "false"?

**Comment by Matten-Matten** [comment]
done.
