### ISSUE TITLE
Add CPU und RAM Usage objekts

### ISSUE THREAD

**Issue by Maja61** [iobroker-community-adapters/ioBroker.enigma2#38]
If its possible please add the CPU und RAM Usage from the enigma receiver to the adapter objects.

**Comment by Matten-Matten** [comment]
Muss ich schauen ob die api mir diese Werte auswirft. falls ja werde ich das in der nächsten Version implementieren.

**Comment by Matten-Matten** [comment]
ich finde keine möglichkeit diese werte über die api auszulesen. Mache deshalb hier zu.

Gruß
Matten Matten
