### ISSUE TITLE
Adapter startet nicht mehr seit Host Update 3.0.14

### ISSUE THREAD

**Issue by dody0007** [iobroker-community-adapters/ioBroker.enigma2#39]
Hallo, seit dem Host Update des iobroker auf 3.0.14 bekomme ich meine VU+ Box nicht mehr über den Enigma Adapter verbunden. Der Adapter startet, verbindet kurz und trennt dann wieder die Verbindung. Das Spielchen wiederholt sich dann immer wieder.
<img width="1280" alt="Bildschirmfoto 2020-04-22 um 15 55 46" src="https://user-images.githubusercontent.com/41072564/79991777-f785af00-84b2-11ea-9a23-f7e76ee0ae4d.png">

**Comment by Matten-Matten** [comment]
@dody0007 
ich brauche schon den ganzen log Ausschnitt ein screenshot reicht mir nicht.

als workaround schonmal den adapter deinstalliert, erneut von github geladen, ein upload gemacht und dann die Instanz neu angelegt?
