### ISSUE TITLE
V1.3.1 - finished with error.. no installation possible

### ISSUE THREAD

**Issue by Ilovegym66** [iobroker-community-adapters/ioBroker.enigma2#40]
Hi, I found the update and want to test it, but iobroker cant install it:
`Fertig mit Fehler: internal/modules/cjs/loader.js:1174 throw err; ^SyntaxError: /opt/iobroker/node_modules/iobroker.enigma2/io-package.json: Unexpected token } in JSON at position 422 at parse () at Object.Module._extensions..json (internal/modules/cjs/loader.js:1171:22) at Module.load (internal/modules/cjs/loader.js:985:32) at Function.Module._load (internal/modules/cjs/loader.js:878:14) at Module.require (internal/modules/cjs/loader.js:1025:19) at require (internal/modules/cjs/helpers.js:72:18) at Upload.uploadAdapter (/opt/iobroker/node_modules/iobroker.js-controller/lib/setup/setupUpload.js:481:19) at /opt/iobroker/node_modules/iobroker.js-controller/lib/setup/setupInstall.js:1781:24 at ChildProcess. (/opt/iobroker/node_modules/iobroker.js-controller/lib/setup/setupInstall.js:478:47) at ChildProcess.emit (events.js:315:20)
`

the installation log:
`$ ./iobroker url "https://github.com/Matten-Matten/ioBroker.enigma2.git"
install https://github.com/Matten-Matten/ioBroker.enigma2/tarball/60286be59af2f382e50c98450183f59063b6f37d
NPM version: 6.14.7
npm install https://github.com/Matten-Matten/ioBroker.enigma2/tarball/60286be59af2f382e50c98450183f59063b6f37d --loglevel error --prefix "/opt/iobroker" (System call)
../src/BluetoothHciSocket.cpp: In static member function ‘static void BluetoothHciSocket::Init(Nan::ADDON_REGISTER_FUNCTION_ARGS_TYPE)’:../src/BluetoothHciSocket.cpp:128:82: error: no matching function for call to ‘v8::FunctionTemplate::GetFunction()’   target->Set(Nan::New("BluetoothHciSocket").ToLocalChecked(), tmpl->GetFunction());                                                                                  ^
In file included from /home/iobroker/.cache/node-gyp/12.18.3/include/node/node.h:67:0,                 from /home/iobroker/.cache/node-gyp/12.18.3/include/node/node_buffer.h:25,                 from ../src/BluetoothHciSocket.cpp:7:/home/iobroker/.cache/node-gyp/12.18.3/include/node/v8.h:6126:46: note: candidate: v8::MaybeLocal<v8::Function> v8::FunctionTemplate::GetFunction(v8::Local<v8::Context>)   V8_WARN_UNUSED_RESULT MaybeLocal<Function> GetFunction(                                              ^/home/iobroker/.cache/node-gyp/12.18.3/include/node/v8.h:6126:46: note:   candidate expects 1 argument, 0 provided
../src/BluetoothHciSocket.cpp: In member function ‘void BluetoothHciSocket::poll()’:../src/BluetoothHciSocket.cpp:251:95: warning: ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::String>, int, v8::Local<v8::Value>*)’ is deprecated [-Wdeprecated-declarations]     Nan::MakeCallback(Nan::New<Object>(this->This), Nan::New("emit").ToLocalChecked(), 2, argv);                                                                                               ^
In file included from ../src/BluetoothHciSocket.cpp:8:0:../../../../nan/nan.h:1047:46: note: declared here   NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(                                              ^../src/BluetoothHciSocket.cpp: In member function ‘void BluetoothHciSocket::emitErrnoError()’:../src/BluetoothHciSocket.cpp:269:109: warning: ‘v8::Local<v8::Value> v8::Object::Get(v8::Local<v8::Value>)’ is deprecated: Use maybe version [-Wdeprecated-declarations]   Local<Function> errorConstructor = Local<Function>::Cast(globalObj->Get(Nan::New("Error").ToLocalChecked()));                                                                                                             ^
In file included from /home/iobroker/.cache/node-gyp/12.18.3/include/node/v8-internal.h:14:0,                 from /home/iobroker/.cache/node-gyp/12.18.3/include/node/v8.h:27,                 from /home/iobroker/.cache/node-gyp/12.18.3/include/node/node.h:67,                 from /home/iobroker/.cache/node-gyp/12.18.3/include/node/node_buffer.h:25,                 from ../src/BluetoothHciSocket.cpp:7:/home/iobroker/.cache/node-gyp/12.18.3/include/node/v8.h:3553:51: note: declared here   V8_DEPRECATED("Use maybe version", Local<Value> Get(Local<Value> key));                                                   ^/home/iobroker/.cache/node-gyp/12.18.3/include/node/v8config.h:328:3: note: in definition of macro ‘V8_DEPRECATED’   declarator __attribute__((deprecated(message)))   ^../src/BluetoothHciSocket.cpp:275:72: error: no matching function for call to ‘v8::Function::NewInstance(int, v8::Local<v8::Value> [1])’   Local<Value> error = errorConstructor->NewInstance(1, constructorArgs);                                                                        ^In file included from /home/iobroker/.cache/node-gyp/12.18.3/include/node/node.h:67:0,                 from /home/iobroker/.cache/node-gyp/12.18.3/include/node/node_buffer.h:25,                 from ../src/BluetoothHciSocket.cpp:7:/home/iobroker/.cache/node-gyp/12.18.3/include/node/v8.h:4281:44: note: candidate: v8::MaybeLocal<v8::Object> v8::Function::NewInstance(v8::Local<v8::Context>, int, v8::Local<v8::Value>*) const   V8_WARN_UNUSED_RESULT MaybeLocal<Object> NewInstance(                                            ^/home/iobroker/.cache/node-gyp/12.18.3/include/node/v8.h:4281:44: note:   candidate expects 3 arguments, 2 provided/home/iobroker/.cache/node-gyp/12.18.3/include/node/v8.h:4284:44: note: candidate: v8::MaybeLocal<v8::Object> v8::Function::NewInstance(v8::Local<v8::Context>) const   V8_WARN_UNUSED_RESULT MaybeLocal<Object> NewInstance(                                            ^/home/iobroker/.cache/node-gyp/12.18.3/include/node/v8.h:4284:44: note:   candidate expects 1 argument, 2 provided
../src/BluetoothHciSocket.cpp:282:93: warning: ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::String>, int, v8::Local<v8::Value>*)’ is deprecated [-Wdeprecated-declarations]   Nan::MakeCallback(Nan::New<Object>(this->This), Nan::New("emit").ToLocalChecked(), 2, argv);                                                                                             ^In file included from ../src/BluetoothHciSocket.cpp:8:0:../../../../nan/nan.h:1047:46: note: declared here   NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(                                              ^
../src/BluetoothHciSocket.cpp: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE BluetoothHciSocket::BindRaw(Nan::NAN_METHOD_ARGS_TYPE)’:../src/BluetoothHciSocket.cpp:395:34: error: no matching function for call to ‘v8::Value::IntegerValue()’       devId = arg0->IntegerValue();                                  ^In file included from /home/iobroker/.cache/node-gyp/12.18.3/include/node/node.h:67:0,                 from /home/iobroker/.cache/node-gyp/12.18.3/include/node/node_buffer.h:25,                 from ../src/BluetoothHciSocket.cpp:7:/home/iobroker/.cache/node-gyp/12.18.3/include/node/v8.h:2705:40: note: candidate: v8::Maybe<long int> v8::Value::IntegerValue(v8::Local<v8::Context>) const   V8_WARN_UNUSED_RESULT Maybe<int64_t> IntegerValue(                                        ^/home/iobroker/.cache/node-gyp/12.18.3/include/node/v8.h:2705:40: note:   candidate expects 1 argument, 0 provided
../src/BluetoothHciSocket.cpp: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE BluetoothHciSocket::BindUser(Nan::NAN_METHOD_ARGS_TYPE)’:../src/BluetoothHciSocket.cpp:417:34: error: no matching function for call to ‘v8::Value::IntegerValue()’       devId = arg0->IntegerValue();                                  ^In file included from /home/iobroker/.cache/node-gyp/12.18.3/include/node/node.h:67:0,                 from /home/iobroker/.cache/node-gyp/12.18.3/include/node/node_buffer.h:25,                 from ../src/BluetoothHciSocket.cpp:7:/home/iobroker/.cache/node-gyp/12.18.3/include/node/v8.h:2705:40: note: candidate: v8::Maybe<long int> v8::Value::IntegerValue(v8::Local<v8::Context>) const   V8_WARN_UNUSED_RESULT Maybe<int64_t> IntegerValue(                                        ^/home/iobroker/.cache/node-gyp/12.18.3/include/node/v8.h:2705:40: note:   candidate expects 1 argument, 0 provided
make: *** [Release/obj.target/binding/src/BluetoothHciSocket.o] Error 1
gyp
 ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2gyp ERR! 
stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)gyp ERR! stack     at ChildProcess.emit (events.js:315:20)gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 4.15.0-112-genericgyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"gyp ERR! cwd /opt/iobroker/node_modules/iobroker.javascript/node_modules/bluetooth-hci-socketgyp ERR! node -v v12.18.3gyp ERR! node-gyp -v v5.1.0gyp ERR! not ok 
ERROR: internal/modules/cjs/loader.js:1174    throw err;    ^SyntaxError: /opt/iobroker/node_modules/iobroker.enigma2/io-package.json: Unexpected token } in JSON at position 422    at parse (<anonymous>)    at Object.Module._extensions..json (internal/modules/cjs/loader.js:1171:22)    at Module.load (internal/modules/cjs/loader.js:985:32)    at Function.Module._load (internal/modules/cjs/loader.js:878:14)    at Module.require (internal/modules/cjs/loader.js:1025:19)    at require (internal/modules/cjs/helpers.js:72:18)    at Upload.uploadAdapter (/opt/iobroker/node_modules/iobroker.js-controller/lib/setup/setupUpload.js:481:19)    at /opt/iobroker/node_modules/iobroker.js-controller/lib/setup/setupInstall.js:1781:24    at ChildProcess.<anonymous> (/opt/iobroker/node_modules/iobroker.js-controller/lib/setup/setupInstall.js:478:47)    at ChildProcess.emit (events.js:315:20)
ERROR: process exited with code 1`

![grafik](https://user-images.githubusercontent.com/36229898/90865485-b505ad80-e392-11ea-8e6d-8dccf7857e06.png)

System: VM Linux Mint 18.3, Node 12.18.3, NPM 6.14.7, js-controller 3.1.6, Admin 4.1.6. If you need any more details, dont hesistate to ask, please.

**Comment by Matten-Matten** [comment]
Installation via npm das selbe?

**Comment by Matten-Matten** [comment]
Bitte erneut installieren und kurze rückmeldung geben ob es funktioniert

**Comment by Matten-Matten** [comment]
problem behoben.
