### ISSUE TITLE
Volume up/down

### ISSUE THREAD

**Issue by SabineTobi** [iobroker-community-adapters/ioBroker.enigma2#41]
Hallo Matten-Matten!

Es wäre praktisch, wenn es auch Attribute für "Volume up" and "Volume down" geben würde. Damit könnte man dann einfach bei Visualisierungen die entsprechenden Tasten der Fernbedienung nachbilden.

In der var PATH wären dazu folgende beiden Zeilen notwendig:
```
VOLUME_UP: '/web/vol?set=up',
VOLUME_DOWN: '/web/vol?set=down',
```
Ich hab jetzt aber nicht geschaut, was sonst noch alles zu ergänzen wäre.

Danke,
Sabine

**Comment by Matten-Matten** [comment]
erledigt.

**Comment by SabineTobi** [comment]
Danke!
