### ISSUE TITLE
Alexa

### ISSUE THREAD

**Issue by lolax80** [iobroker-community-adapters/ioBroker.enigma2#42]
Hallo,

was passiert wenn ich in der Config des Adapters Alexa einschalte?
Brauche ich zusätzlich noch ein Plugin auf der Enigma Box?

**Comment by Matten-Matten** [comment]
dann tauchen die Datenpunkte  `Alexa_Command.Mute` & `Alexa_Command.Standby` auf die du dann zur Alexasteuerung nutzen kannst.

Gruß
Matten Matten
