### ISSUE TITLE
Work on adapter enigma2 canceled. Project taker wanted

### ISSUE THREAD

**Issue by Matten-Matten** [iobroker-community-adapters/ioBroker.enigma2#44]
Ich habe die Arbeit am Adapter enigma2 eingestellt.  
**Projekt Übernehmer gesucht!**

Gruß
Matten Matten

**Comment by dslraser** [comment]
https://github.com/iobroker-community-adapters/info

Nachfrage im Forum
https://forum.iobroker.net/post/486363

Antwort im Forum Siehe hier
https://forum.iobroker.net/post/488002

**Comment by joetriskaide** [comment]
Hi Leute, ich habe iobroker vor einige Wochen entdeckt und bin total begeistert. Ich könnte mir vorstellen, den enigma-adapter zu übernehmen. Meine Box ist allerdings schon älter :-) eine Sogno HD800 denke ich. 
Ich kenne das OpenWebIF-API,  HTML und Javascript ganz gut --- den Rest lerne ich schon,. Ich bräuchte sicher etwas Anschub bei der Programmierung eines iobroker-Adapters - das sollte schon werden.
Zur Zeit versuche ich noch, meine 3T-Rolladen (rolladenmotoer-24.de, Dooya Fernsteuerung in iobroker zu implementieren - wenn das klappt, hätte ich Zeit für die Enigma.

**Comment by Matten-Matten** [comment]
Now is a Community Adapter.
