### ISSUE TITLE
Info im Log mit js-controller 3.3.x

### ISSUE THREAD

**Issue by UweRP** [iobroker-community-adapters/ioBroker.enigma2#48]
Auch wenn es nicht zeitnah behoben wird halte ich es mal hier fest.

```
enigma2.0 | 2021-05-08 07:55:41.895 | info | (2488) State value to set for "enigma2.0.enigma2.MESSAGE_ANSWER" has to be type "integer" but received type "string"
enigma2.0 | 2021-05-08 07:55:41.874 | info | (2488) State value to set for "enigma2.0.enigma2.EVENTREMAINING" has to be type "number" but received type "string"
enigma2.0 | 2021-05-08 07:55:41.874 | info | (2488) State value to set for "enigma2.0.enigma2.EVENTDURATION" has to be type "number" but received type "string"
enigma2.0 | 2021-05-08 07:55:36.821 | info | (2488) State value to set for "enigma2.0.enigma2.MESSAGE_ANSWER" has to be type "integer" but received type "string"

``` 

Das zusammen mit enigma2 1.3.2

**Comment by ppb1308** [comment]
Hier auch.

**Comment by TDCroPower** [comment]
Leider ist der DEV ja aus dem Projekt raus, führt jemand das Projekt mittlerweile weiter oder hat einen funktionierenden Fork mit einem Fix der Datenpunkte erstellt?

**Comment by TDCroPower** [comment]
Ich habe den Fehler mit dem falschen Type in meinem Fork korrigiert und die Meldungen sind weg...
https://github.com/TDCroPower/ioBroker.enigma2

wer meinen Fork installieren will muss lediglich über die Katze >>> Benutzerdefiniert folgendes eingeben...
TDCroPower/ioBroker.enigma2#6ddcb5aeddc18a7f53295a239c28beefcd0a1ae0

Ich werde mal einen Pull Request dazu zu erstellen, ob er von irgend jemanden übernommen wird ist halt die Frage!?
Pull Request: https://github.com/Matten-Matten/ioBroker.enigma2/pull/49

**Comment by TDCroPower** [comment]
https://github.com/Matten-Matten/ioBroker.enigma2/pull/49

**Comment by TDCroPower** [comment]
@Matten-Matten kannst das Issue dann auch schließen nach deinem Merge, danke fürs schnelle reagieren!

**Comment by ppb1308** [comment]
> Ich habe den Fehler mit dem falschen Type in meinem Fork korrigiert und die Meldungen sind weg...
> https://github.com/TDCroPower/ioBroker.enigma2
> 
> wer meinen Fork installieren will muss lediglich über die Katze >>> Benutzerdefiniert folgendes eingeben...
> TDCroPower/ioBroker.enigma2#6ddcb5aeddc18a7f53295a239c28beefcd0a1ae0
Leider auch nach Update aus Deinem Fork immer noch Fehler im Protokoll:
State value to set for "enigma2.0.enigma2.EVENTREMAINING" has to be type "number" but received type "string"
State value to set for "enigma2.0.enigma2.EVENTDURATION" has to be type "number" but received type "string"
State value to set for "enigma2.0.enigma2.MESSAGE_ANSWER" has to be type "integer" but received type "string"

Sollte ich nach den folgenden Schritten noch irgendwas löschen oder tun?
1. Update aus der gegebenen URL mit "Katze" und Benutzerdefiniert
2. Dateiupload
3. Stoppen Instanz & starten Instanz

**Comment by TDCroPower** [comment]
@ppb1308 es wurde von @Matten-Matten schon ins Hauptprojekt gemerged, kannst also den commit von hier jetzt nehmen...
Matten-Matten/ioBroker.enigma2#af05c9293f8e536018587b5fd5973095811fa696

Ich würde dir empfehlen..

1. Instanz stoppen
2. unter Objekte den enigma2 Tree komplett löschen
3. Update aus der gegebenen URL mit "Katze" und Benutzerdefiniert
4. starten Instanz

**Comment by Matten-Matten** [comment]
ist jetzt auch auf npm.

**Comment by TDCroPower** [comment]
@Matten-Matten was bedeutet "ist auf npm"?
Wie kann man denn den Adapter direkt per ioBroker updaten?
Weiterhin über die "Katze"?

edit: ok klassisch über Katze >>> Beliebig und dann mit Matten-Matten/ioBroker.enigma2 wurde das Update installiert.

**Comment by Matten-Matten** [comment]
Oder per Kommando Zeile 
`npm i iobroker.enigma2`

**Comment by ppb1308** [comment]
> @ppb1308 es wurde von @Matten-Matten schon ins Hauptprojekt gemerged, kannst also den commit von hier jetzt nehmen...
> Matten-Matten/ioBroker.enigma2#af05c9293f8e536018587b5fd5973095811fa696
> 
> Ich würde dir empfehlen..
> 
> 1. Instanz stoppen
> 2. unter Objekte den enigma2 Tree komplett löschen
> 3. Update aus der gegebenen URL mit "Katze" und Benutzerdefiniert
> 4. starten Instanz

Danke @Matten-Matten und @TDCroPower , hat funktioniert.
