### ISSUE TITLE
Type String anstatt Number

### ISSUE THREAD

**Issue by Negalein** [iobroker-community-adapters/ioBroker.enigma2#51]
Ich bekomm seit JS-Controller 3.3.14 laufend solche Meldungen.

```
enigma2.0 | 2021-07-08 16:04:56.849 | info | State value to set for "enigma2.0.enigma2.EVENTREMAINING" has to be type "number" but received type "string"
enigma2.0 | 2021-07-08 16:04:56.848 | info | State value to set for "enigma2.0.enigma2.EVENTDURATION" has to be type "number" but received type "string"
enigma2.0 | 2021-07-08 16:04:56.844 | info | State value to set for "enigma2.0.enigma2.MESSAGE_ANSWER" has to be type "integer" but received type "string"
```

**Comment by Matten-Matten** [comment]
#48  

Adapter neu installieren.

**Comment by thomasklein1975** [comment]
hi,
ich habe die selben Infos im Log. Auch nachdem ich den Adapter 1.3.2 neu installiert hatte.

`State value to set for "enigma2.0.enigma2.MESSAGE_ANSWER" has to be type "integer" but received type "string"`

Node.js: v14.17.0 
NPM: 6.14.13

Kann ich das logging deaktivieren?

**Comment by dodo-dk** [comment]
Es ist wichtig unter Objekte den ganzen Tree zu löschen. Damit nach dem Update die ganzen Datenpunkte neu erstellt werden. Dann ist Ruhe. 
so wie hier beschrieben:

https://github.com/Matten-Matten/ioBroker.enigma2/issues/48#issuecomment-858677571

**Comment by thomasklein1975** [comment]
ok danke,

hab das jetzt noch drin nach der Installation:
`
<html>
<body>


enigma2.1 | 2021-09-17 07:46:25.529 | warn | (14851) State "enigma2.1.Message.MESSAGE_ANSWER" has no existing object, this might lead to an error in future versions
-- | -- | -- | --
enigma2.1 | 2021-09-17 07:46:25.528 | warn | (14851) Read-only state "enigma2.1.enigma2.WEB_IF_VERSION" has been written without ack-flag with value ""
enigma2.1 | 2021-09-17 07:46:25.526 | info | (14851) State value to set for "enigma2.1.enigma2.VOLUME" has to be type "number" but received type "string"
enigma2.1 | 2021-09-17 07:46:25.526 | warn | (14851) Read-only state "enigma2.1.enigma2.VOLUME" has been written without ack-flag with value ""
enigma2.1 | 2021-09-17 07:46:25.524 | warn | (14851) Read-only state "enigma2.1.enigma2.PROGRAMM_INFO" has been written without ack-flag with value ""
enigma2.1 | 2021-09-17 07:46:25.522 | warn | (14851) Read-only state "enigma2.1.enigma2.PROGRAMM_AFTER_INFO" has been written without ack-flag with value ""
enigma2.1 | 2021-09-17 07:46:25.521 | warn | (14851) Read-only state "enigma2.1.enigma2.PROGRAMM_AFTER" has been written without ack-flag with value ""
enigma2.1 | 2021-09-17 07:46:25.520 | warn | (14851) Read-only state "enigma2.1.enigma2.PROGRAMM" has been written without ack-flag with value ""
enigma2.1 | 2021-09-17 07:46:25.518 | warn | (14851) Read-only state "enigma2.1.enigma2.NETWORK" has been written without ack-flag with value ""
enigma2.1 | 2021-09-17 07:46:25.517 | info | (14851) State value to set for "enigma2.1.enigma2.MUTED" has to be type "boolean" but received type "string"
enigma2.1 | 2021-09-17 07:46:25.516 | warn | (14851) Read-only state "enigma2.1.enigma2.MUTED" has been written without ack-flag with value ""
enigma2.1 | 2021-09-17 07:46:25.515 | warn | (14851) Read-only state "enigma2.1.enigma2.MODEL" has been written without ack-flag with value ""
enigma2.1 | 2021-09-17 07:46:25.514 | info | (14851) State value to set for "enigma2.1.enigma2.MESSAGE_ANSWER" has to be type "integer" but received type "string"
enigma2.1 | 2021-09-17 07:46:25.513 | warn | (14851) Read-only state "enigma2.1.enigma2.MESSAGE_ANSWER" has been written without ack-flag with value ""
enigma2.1 | 2021-09-17 07:46:25.512 | info | (14851) State value to set for "enigma2.1.enigma2.EVENTREMAINING" has to be type "number" but received type "string"
enigma2.1 | 2021-09-17 07:46:25.511 | warn | (14851) Read-only state "enigma2.1.enigma2.EVENTREMAINING" has been written without ack-flag with value ""
enigma2.1 | 2021-09-17 07:46:25.509 | info | (14851) State value to set for "enigma2.1.enigma2.EVENTDURATION" has to be type "number" but received type "string"
enigma2.1 | 2021-09-17 07:46:25.508 | warn | (14851) Read-only state "enigma2.1.enigma2.EVENTDURATION" has been written without ack-flag with value ""
enigma2.1 | 2021-09-17 07:46:25.507 | warn | (14851) Read-only state "enigma2.1.enigma2.EVENTDESCRIPTION" has been written without ack-flag with value ""
enigma2.1 | 2021-09-17 07:46:25.505 | warn | (14851) Read-only state "enigma2.1.enigma2.CHANNEL_SERVICEREFERENCE" has been written without ack-flag with value ""
enigma2.1 | 2021-09-17 07:46:25.503 | warn | (14851) Read-only state "enigma2.1.enigma2.CHANNEL_PICON" has been written without ack-flag with value ""
enigma2.1 | 2021-09-17 07:46:25.502 | warn | (14851) Read-only state "enigma2.1.enigma2.CHANNEL" has been written without ack-flag with value ""
enigma2.1 | 2021-09-17 07:46:25.499 | warn | (14851) Read-only state "enigma2.1.enigma2.BOX_IP" has been written without ack-flag with value ""
enigma2.1 | 2021-09-17 07:46:25.468 | info | (14851) enigma2: 192.168.0.39:81 ist nicht erreichbar!
enigma2.1 | 2021-09-17 07:46:17.398 | warn | (14851) State "enigma2.1.enigma2-CONNECTION" has no existing object, this might lead to an error in future versions
enigma2.1 | 2021-09-17 07:46:17.396 | warn | (14851) State "enigma2.1.Message.Timeout" has no existing object, this might lead to an error in future versions
enigma2.1 | 2021-09-17 07:46:17.395 | warn | (14851) State "enigma2.1.Message.Type" has no existing object, this might lead to an error in future versions
enigma2.1 | 2021-09-17 07:46:17.392 | warn | (14851) This object will not be created in future versions. Please report this to the developer.
enigma2.1 | 2021-09-17 07:46:17.391 | warn | (14851) Object enigma2.1.enigma2.MESSAGE_ANSWER is invalid: obj.common.type has an invalid value (integer) but has to be one of number, string, boolean, array, object, mixed, file, json
enigma2.1 | 2021-09-17 07:46:17.337 | info | (14851) starting Polling every 5000 ms
enigma2.1 | 2021-09-17 07:46:17.290 | info | (14851) starting. Version 1.3.2 in /opt/iobroker/node_modules/iobroker.enigma2, node: v14.17.0, js-controller: 3.3.15


</body>
</html>`

**Comment by Matten-Matten** [comment]
Das kann an der neuen admin Version liegen.
Da müssen Abänderungen im Adapter vorgenommen werden.
