### ISSUE TITLE
JS-Controller wrong type of field

### ISSUE THREAD

**Issue by metaxa1** [iobroker-community-adapters/ioBroker.enigma2#52]
State value to set for "enigma2.0.enigma2.EVENTREMAINING" has to be type "number" but received type "string" 

<html><body>

enigma2.0 | 2021-08-05 21:50:34.332 | info | (16943) State value to set for "enigma2.0.enigma2.EVENTREMAINING" has to be type "number" but received type "string"
-- | -- | -- | --
enigma2.0 | 2021-08-05 21:50:34.330 | info | (16943) State value to set for "enigma2.0.enigma2.EVENTDURATION" has to be type "number" but received type "string"

</body>

<html><body>

enigma2.0 | 2021-08-05 22:47:18.575 | warn | (16943) State "enigma2.0.Message.MESSAGE_ANSWER" has no existing object, this might lead to an error in future versions
-- | -- | -- | --
enigma2.0 | 2021-08-05 22:47:18.574 | warn | (16943) Read-only state "enigma2.0.enigma2.WEB_IF_VERSION" has been written without ack-flag with value ""
enigma2.0 | 2021-08-05 22:47:18.572 | warn | (16943) Read-only state "enigma2.0.enigma2.VOLUME" has been written without ack-flag with value ""
enigma2.0 | 2021-08-05 22:47:18.566 | warn | (16943) Read-only state "enigma2.0.enigma2.PROGRAMM_INFO" has been written without ack-flag with value ""
enigma2.0 | 2021-08-05 22:47:18.565 | warn | (16943) Read-only state "enigma2.0.enigma2.PROGRAMM_AFTER_INFO" has been written without ack-flag with value ""
enigma2.0 | 2021-08-05 22:47:18.565 | warn | (16943) Read-only state "enigma2.0.enigma2.PROGRAMM_AFTER" has been written without ack-flag with value ""
enigma2.0 | 2021-08-05 22:47:18.564 | warn | (16943) Read-only state "enigma2.0.enigma2.PROGRAMM" has been written without ack-flag with value ""
enigma2.0 | 2021-08-05 22:47:18.564 | warn | (16943) Read-only state "enigma2.0.enigma2.NETWORK" has been written without ack-flag with value ""
enigma2.0 | 2021-08-05 22:47:18.563 | warn | (16943) Read-only state "enigma2.0.enigma2.MUTED" has been written without ack-flag with value ""
enigma2.0 | 2021-08-05 22:47:18.563 | warn | (16943) Read-only state "enigma2.0.enigma2.MODEL" has been written without ack-flag with value ""
enigma2.0 | 2021-08-05 22:47:18.562 | warn | (16943) Read-only state "enigma2.0.enigma2.MESSAGE_ANSWER" has been written without ack-flag with value ""

</body>
</html>
</html>

**Comment by denjo1982** [comment]
habe auch das gleiche problem 
State value to set for "enigma2.0.enigma2.EVENTREMAINING" has to be type "number" but received type "string"

**Comment by Matten-Matten** [comment]
#48

Adapter löschen und neu installieren.
