### ISSUE TITLE
set_volume liefert string anstelle number retour

### ISSUE THREAD

**Issue by metaxa1** [iobroker-community-adapters/ioBroker.enigma2#56]
Beim setzen der Lautstärke über den DP set_volume kommt folgende Fehlermeldung:
`<html>
<body>
<pre class="markdown-highlight" style="box-sizing: border-box; overflow: auto; font-family: Menlo, Monaco, Consolas, &quot;Courier New&quot;, monospace; font-size: 13px; display: block; padding: 9.5px; margin: 1rem 0px 10px; line-height: 1.42857; word-break: break-all; overflow-wrap: break-word; color: rgb(51, 51, 51); background-color: rgb(255, 255, 255); border: none; border-radius: 0px; max-height: 350px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><code class="hljs sql" data-lines="1" style="box-sizing: border-box; font-family: Menlo, Monaco, Consolas, &quot;Courier New&quot;, monospace; font-size: inherit; padding: 0.5em; color: rgb(230, 225, 220); background: rgb(35, 35, 35); border-radius: 0px; white-space: pre; display: inline-block; overflow-x: auto; overflow-wrap: normal; min-width: 100%;">

  | enigma2.0
-- | --
  | 2021-12-28 09:58:54.682	info	State value to set for "enigma2.0.command.SET_VOLUME" has to be type "number" but received type "string"

</code></pre>
</body>
</html>
`

`<html>
<body>

enigma2.0
--
  | 2021-12-28 11:39:52.144	debug	Box Muted:false
  |  
  | enigma2.0
  | 2021-12-28 11:39:52.144	debug	Box Volume:10
  |  
  | enigma2.0
  | 2021-12-28 11:39:52.143	debug	evaluating response for command 'GETVOLUME': {"e2volume":{"e2result":["True"],"e2resulttext":["Status"],"e2current":["10"],"e2ismuted":["False"]}}
  |  
  | enigma2.0
  | 2021-12-28 11:39:52.103	info	State value to set for "enigma2.0.command.SET_VOLUME" has to be type "number" but received type "string"
  |  
  | enigma2.0
  | 2021-12-28 11:39:52.076	debug	using authorization with user 'root'
  |  
  | enigma2.0
  | 2021-12-28 11:39:52.062	debug	creating request for command 'GETVOLUME' (deviceId: [object Object], host: 192.168.0.58, port: 80, path: '/web/vol')
  |  
  | enigma2.0
  | 2021-12-28 11:39:51.996	debug	using authorization with user 'root'
  |  
  | enigma2.0
  | 2021-12-28 11:39:51.994	debug	creating request for command 'NONE' (deviceId: 1, host: 192.168.0.58, port: 80, path: '/web/vol?set=set10')

</body>
</html>`

Hier der Thread im Forum dazu: [Forum](https://forum.iobroker.net/topic/46771/wozu-ist-der-ack-flag-da/23?_=1640685010290)

**Comment by Matten-Matten** [comment]
in 1.3.4.
