### ISSUE TITLE
Timer Start und Endzeit als 13 stelligen String

### ISSUE THREAD

**Issue by peoples0815** [iobroker-community-adapters/ioBroker.enigma2#59]
Hi,

wäre es möglich Generierung des Timestamps für Start und Endzeit in einen 13 stelligen Wert zu ändern wie er auch bei den Datenpunkten bei lc und ts Verwendung findet?

Hierzu müssten nur die Zeilen 763 und 764:

`starTime: timerItem["e2timebegin"].toString()`
`endTime: timerItem["e2timeend"].toString()`

auf:

`starTime: (timerItem["e2timebegin"]*1000).toString()`
`endTime: (timerItem["e2timeend"]*1000).toString()`

geändert werden.

**Comment by Matten-Matten** [comment]
in 1.3.4
