### ISSUE TITLE
[js-controller 5] After host upgrade to 5.0.2 no connection to enigma2 box

### ISSUE THREAD

**Issue by lhoem** [iobroker-community-adapters/ioBroker.enigma2#90]
Hello,

after host upgrade to 5.0.2 the adapter won't connect to the box.

host.TECRA-A11 2023-06-12 17:17:21.577	info	Rebuild for adapter system.adapter.enigma2.0 not successful in 3 tries. Adapter will not be restarted again. Please execute "npm install --production" in adapter directory manually.
host.TECRA-A11 2023-06-12 17:17:21.577	error	instance system.adapter.enigma2.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
host.TECRA-A11 2023-06-12 17:17:21.577	error	Caught by controller[0]: }
host.TECRA-A11 2023-06-12 17:17:21.576	error	Caught by controller[0]: ]
host.TECRA-A11 2023-06-12 17:17:21.576	error	Caught by controller[0]: '/opt/iobroker/node_modules/iobroker.enigma2/main.js'
host.TECRA-A11 2023-06-12 17:17:21.576	error	Caught by controller[0]: '/opt/iobroker/node_modules/iobroker.enigma2/lib/utils.js',
host.TECRA-A11 2023-06-12 17:17:21.576	error	Caught by controller[0]: requireStack: [
host.TECRA-A11 2023-06-12 17:17:21.576	error	Caught by controller[0]: code: 'MODULE_NOT_FOUND',
host.TECRA-A11 2023-06-12 17:17:21.575	error	Caught by controller[0]: at Module.require (node:internal/modules/cjs/loader:1093:19) {
host.TECRA-A11 2023-06-12 17:17:21.575	error	Caught by controller[0]: at Function.Module._load (node:internal/modules/cjs/loader:904:12)
host.TECRA-A11 2023-06-12 17:17:21.575	error	Caught by controller[0]: at Module.load (node:internal/modules/cjs/loader:1069:32)
host.TECRA-A11 2023-06-12 17:17:21.575	error	Caught by controller[0]: at Object.Module._extensions..js (node:internal/modules/cjs/loader:1245:10)
host.TECRA-A11 2023-06-12 17:17:21.575	error	Caught by controller[0]: at Module._compile (node:internal/modules/cjs/loader:1191:14)
host.TECRA-A11 2023-06-12 17:17:21.575	error	Caught by controller[0]: at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.enigma2/lib/utils.js:46:25)
host.TECRA-A11 2023-06-12 17:17:21.575	error	Caught by controller[0]: at require (node:internal/modules/cjs/helpers:108:18)
host.TECRA-A11 2023-06-12 17:17:21.574	error	Caught by controller[0]: at Module.require (node:internal/modules/cjs/loader:1093:19)
host.TECRA-A11 2023-06-12 17:17:21.574	error	Caught by controller[0]: at Function.Module._load (node:internal/modules/cjs/loader:866:27)
host.TECRA-A11 2023-06-12 17:17:21.574	error	Caught by controller[0]: at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1021:15)
host.TECRA-A11 2023-06-12 17:17:21.574	error	Caught by controller[0]: - /opt/iobroker/node_modules/iobroker.enigma2/main.js
host.TECRA-A11 2023-06-12 17:17:21.574	error	Caught by controller[0]: - /opt/iobroker/node_modules/iobroker.enigma2/lib/utils.js
host.TECRA-A11 2023-06-12 17:17:21.574	error	Caught by controller[0]: Require stack:
host.TECRA-A11 2023-06-12 17:17:21.574	error	Caught by controller[0]: Error: Cannot find module '/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js'
host.TECRA-A11 2023-06-12 17:17:21.573	error	Caught by controller[0]: ^
host.TECRA-A11 2023-06-12 17:17:21.573	error	Caught by controller[0]: throw err;
host.TECRA-A11 2023-06-12 17:17:21.573	error	Caught by controller[0]: node:internal/modules/cjs/loader:1024
host.TECRA-A11 2023-06-12 17:17:21.060	info	instance system.adapter.enigma2.0 started with pid 88870

**Versions:**  
 - Adapter version: 1.3.2
JS-Controller version: 7.0.5
Node version: 16.19.1
Operating system: ubuntu

What can I do?

**Comment by mcm1957** [comment]
Not sure which upgrade you refer to because

- "host upgrade to 5.0.2"  looks like upgrade of js-controler to V5 beta 
- "JS-Controller version: 7.0.5" specifies a non existing version

I assume this issue refers to js-controller5 (beta) upgrade.

McM1957

**Comment by mcm1957** [comment]
**Enigma2 must be upgraded to 1.4.0 or newer to support js-controller5.**

Please try to install current github release (1.5.0) as Enigma is not yet available at repositories.

Note: This fact is listed at beta info too, see https://forum.iobroker.net/topic/66108/js-controller-5-0-x-jetzt-in-der-beta
