### ISSUE TITLE
Adapter bring Fehler nach Update JS-Controller 5.0.3

### ISSUE THREAD

**Issue by cybermann22** [iobroker-community-adapters/ioBroker.enigma2#91]
`<html>
<body>

host.iobroker | 2023-06-14 14:14:36.151 | info | "system.adapter.enigma2.0" disabled
-- | -- | -- | --
host.iobroker | 2023-06-14 14:14:25.962 | info | Rebuild for adapter system.adapter.enigma2.0 not successful in 3 tries. Adapter will not be restarted again. Please execute "npm install --production" in adapter directory manually.
host.iobroker | 2023-06-14 14:14:25.961 | error | instance system.adapter.enigma2.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
host.iobroker | 2023-06-14 14:14:25.961 | error | Caught by controller[0]: }
host.iobroker | 2023-06-14 14:14:25.961 | error | Caught by controller[0]: ]
host.iobroker | 2023-06-14 14:14:25.961 | error | Caught by controller[0]: '/opt/iobroker/node_modules/iobroker.enigma2/main.js'
host.iobroker | 2023-06-14 14:14:25.961 | error | Caught by controller[0]: '/opt/iobroker/node_modules/iobroker.enigma2/lib/utils.js',
host.iobroker | 2023-06-14 14:14:25.961 | error | Caught by controller[0]: requireStack: [
host.iobroker | 2023-06-14 14:14:25.961 | error | Caught by controller[0]: code: 'MODULE_NOT_FOUND',
host.iobroker | 2023-06-14 14:14:25.961 | error | Caught by controller[0]: at Module.require (node:internal/modules/cjs/loader:1098:19) {
host.iobroker | 2023-06-14 14:14:25.961 | error | Caught by controller[0]: at Function.Module._load (node:internal/modules/cjs/loader:909:12)
host.iobroker | 2023-06-14 14:14:25.961 | error | Caught by controller[0]: at Module.load (node:internal/modules/cjs/loader:1074:32)
host.iobroker | 2023-06-14 14:14:25.961 | error | Caught by controller[0]: at Object.Module._extensions..js (node:internal/modules/cjs/loader:1250:10)
host.iobroker | 2023-06-14 14:14:25.961 | error | Caught by controller[0]: at Module._compile (node:internal/modules/cjs/loader:1196:14)
host.iobroker | 2023-06-14 14:14:25.961 | error | Caught by controller[0]: at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.enigma2/lib/utils.js:46:25)
host.iobroker | 2023-06-14 14:14:25.961 | error | Caught by controller[0]: at require (node:internal/modules/cjs/helpers:108:18)
host.iobroker | 2023-06-14 14:14:25.960 | error | Caught by controller[0]: at Module.require (node:internal/modules/cjs/loader:1098:19)
host.iobroker | 2023-06-14 14:14:25.960 | error | Caught by controller[0]: at Function.Module._load (node:internal/modules/cjs/loader:871:27)
host.iobroker | 2023-06-14 14:14:25.960 | error | Caught by controller[0]: at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1026:15)
host.iobroker | 2023-06-14 14:14:25.960 | error | Caught by controller[0]: - /opt/iobroker/node_modules/iobroker.enigma2/main.js
host.iobroker | 2023-06-14 14:14:25.960 | error | Caught by controller[0]: - /opt/iobroker/node_modules/iobroker.enigma2/lib/utils.js
host.iobroker | 2023-06-14 14:14:25.960 | error | Caught by controller[0]: Require stack:
host.iobroker | 2023-06-14 14:14:25.960 | error | Caught by controller[0]: Error: Cannot find module '/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js'
host.iobroker | 2023-06-14 14:14:25.960 | error | Caught by controller[0]: ^
host.iobroker | 2023-06-14 14:14:25.960 | error | Caught by controller[0]: throw err;
host.iobroker | 2023-06-14 14:14:25.960 | error | Caught by controller[0]: node:internal/modules/cjs/loader:1029
host.iobroker | 2023-06-14 14:14:25.415 | info | instance system.adapter.enigma2.0 started with pid 24375
host.iobroker | 2023-06-14 14:14:25.371 | info | "system.adapter.enigma2.0" enabled

</body>
</html>`

**Comment by mcm1957** [comment]
@cybermann22 
Welche Adapterversion hats du installiert?
js-controller sollte 5.0.2 sein - oder?
Node ??

Bitte IMMER die im Einsatz befindlichen Versionen angeben.

----------

Zum Problem an sich:
js-controller 5 sollte ab 1.4.0 funktionieren. Bitte sicherstellen, dass diese oder besser noch 1.5.0 installiert ist.

**Comment by cybermann22** [comment]
> @cybermann22 Welche Adapterversion hats du installiert? js-controller sollte 5.0.2 sein - oder? Node ??
> 
> Bitte IMMER die im Einsatz befindlichen Versionen angeben.
> 
> Zum Problem an sich: js-controller 5 sollte ab 1.4.0 funktionieren. Bitte sicherstellen, dass diese oder besser noch 1.5.0 installiert ist.

Hi,
ich habe Adapter Version  v1.3.4 und JS-Controller 5.0.3

/usr/bin/nodejs                      
/usr/bin/node                               
/usr/bin/npm                               
/usr/bin/npx                                
v16.20.0                                   
v16.20.0                                                                                  
8.19.4                                   
8.19.4

**Comment by mcm1957** [comment]
Ok, dann adapter updaten. Das sollte es gewesen sein. js-controller Kompatibilität ist in 1.4.0 lt. Release notes.
