### ISSUE TITLE
Adapter not working after Update on Iobroker

### ISSUE THREAD

**Issue by linux150** [iobroker-community-adapters/ioBroker.enigma2#96]
Hi 
I did made the whole update on iobroker.
JS-Controller update to 5.0.5
After that enigma adapter not working 

`<html>
<body>

host.iobroker | 2023-06-28 07:33:34.202 | info | Rebuild for adapter system.adapter.enigma2.0 not successful in 3 tries. Adapter will not be restarted again. Please execute "npm install --production" in adapter directory manually.
-- | -- | -- | --
host.iobroker | 2023-06-28 07:33:34.202 | error | instance system.adapter.enigma2.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
host.iobroker | 2023-06-28 07:33:34.202 | error | Caught by controller[1]: Node.js v18.16.0
host.iobroker | 2023-06-28 07:33:34.202 | error | Caught by controller[0]: }
host.iobroker | 2023-06-28 07:33:34.202 | error | Caught by controller[0]: ]
host.iobroker | 2023-06-28 07:33:34.202 | error | Caught by controller[0]: '/opt/iobroker/node_modules/iobroker.enigma2/main.js'
host.iobroker | 2023-06-28 07:33:34.202 | error | Caught by controller[0]: '/opt/iobroker/node_modules/iobroker.enigma2/lib/utils.js',
host.iobroker | 2023-06-28 07:33:34.202 | error | Caught by controller[0]: requireStack: [
host.iobroker | 2023-06-28 07:33:34.202 | error | Caught by controller[0]: code: 'MODULE_NOT_FOUND',
host.iobroker | 2023-06-28 07:33:34.202 | error | Caught by controller[0]: at Module.require (node:internal/modules/cjs/loader:1141:19) {
host.iobroker | 2023-06-28 07:33:34.202 | error | Caught by controller[0]: at Module._load (node:internal/modules/cjs/loader:958:12)
host.iobroker | 2023-06-28 07:33:34.202 | error | Caught by controller[0]: at Module.load (node:internal/modules/cjs/loader:1117:32)
host.iobroker | 2023-06-28 07:33:34.202 | error | Caught by controller[0]: at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
host.iobroker | 2023-06-28 07:33:34.202 | error | Caught by controller[0]: at Module._compile (node:internal/modules/cjs/loader:1254:14)
host.iobroker | 2023-06-28 07:33:34.202 | error | Caught by controller[0]: at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.enigma2/lib/utils.js:46:25)
host.iobroker | 2023-06-28 07:33:34.202 | error | Caught by controller[0]: at require (node:internal/modules/cjs/helpers:110:18)
host.iobroker | 2023-06-28 07:33:34.202 | error | Caught by controller[0]: at Module.require (node:internal/modules/cjs/loader:1141:19)
host.iobroker | 2023-06-28 07:33:34.202 | error | Caught by controller[0]: at Module._load (node:internal/modules/cjs/loader:920:27)
host.iobroker | 2023-06-28 07:33:34.202 | error | Caught by controller[0]: at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
host.iobroker | 2023-06-28 07:33:34.202 | error | Caught by controller[0]: - /opt/iobroker/node_modules/iobroker.enigma2/main.js
host.iobroker | 2023-06-28 07:33:34.202 | error | Caught by controller[0]: - /opt/iobroker/node_modules/iobroker.enigma2/lib/utils.js
host.iobroker | 2023-06-28 07:33:34.202 | error | Caught by controller[0]: Require stack:
host.iobroker | 2023-06-28 07:33:34.202 | error | Caught by controller[0]: Error: Cannot find module '/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js'
host.iobroker | 2023-06-28 07:33:34.202 | error | Caught by controller[0]: ^
host.iobroker | 2023-06-28 07:33:34.202 | error | Caught by controller[0]: throw err;
host.iobroker | 2023-06-28 07:33:34.202 | error | Caught by controller[0]: node:internal/modules/cjs/loader:1078
host.iobroker | 2023-06-28 07:33:33.932 | info | instance system.adapter.enigma2.0 started with pid 528721

</body>
</html>`

LG
linux150

**Comment by mcm1957** [comment]
Please always state the used versions when creating a issue:

Adapter Version: ???
js-Controller version: 5.0.5
Node Version:

**Comment by linux150** [comment]
Hi sorry, iob diag result:
Nodejs-Installation:    /usr/bin/nodejs         v18.16.0
                        /usr/bin/node           v18.16.0
                        /usr/local/bin/npm              6.14.16
                        /usr/local/bin/npx              6.14.16
ioBroker Core:          js-controller           5.0.5
                        admin                   6.5.9
Adapter Version 1.5.0

**Comment by mcm1957** [comment]
Thanks:
But the most important info WHICH VERSION OF ENIGMA2 is installed is still missing :-)

OK - I was too fast to ask :-)

**Comment by linux150** [comment]
Updated: 1.5.0

**Comment by mcm1957** [comment]
sorry to ask,

but are you absolutly sure that you have installed 1.5.0? Ist this version logged during startup?

Module lib/utils is no longer present since 1.4.x. So currently I do not have a glue why the startup tries to load this module. At the first step it looks like you still have the older release (1.3.x) which does not support js.controller 5 (see release notes).

Did you install the adapter from iobroker-community-adapters/iobroker.engima2 as github installation or from another source?
Could you try to reinstall the adapter?

**Comment by linux150** [comment]
Sorry my mistake, definitly an old version. Deinstalled and now try to install new, but cant find in Adapters.

**Comment by mcm1957** [comment]
Enigma2 is not available at repositories yet (and never was). Request to add it to latest is pending.

You must install it via Github in expert mode

URL: https://github.com/iobroker-community-adapters/ioBroker.enigma2

![image](https://github.com/iobroker-community-adapters/ioBroker.enigma2/assets/28575778/3d85323b-c1c5-4c1a-8946-356a8ac91a46)

**Comment by linux150** [comment]
Trying but not working ... never ending story.
Did update Proxmox, iob container, Restart all but the install is not working ...
![image](https://github.com/iobroker-community-adapters/ioBroker.enigma2/assets/2489804/7805c119-829d-4fb8-b429-444bb27d1d7b)

Ich spiele jetzt das Backup ein, update dann den Adapter und teste dann nochmal mit dem kompletten Upgrade...

**Comment by linux150** [comment]
Reinstalled my proxmox backup, updated the adapter and then updated js-controller.
Working again with few debug messages, maybe you can take a look.
![image](https://github.com/iobroker-community-adapters/ioBroker.enigma2/assets/2489804/394f5f93-bcee-4789-b13c-58a690d957e9)

Greetings, and thanks for your help!
Martin

**Comment by mcm1957** [comment]
Thanks for the feedback.

Please feel free to open another issue this the above infos / errors (as text). This should be investigated bust handling a screenshot in issues is a little bit complicated.
